# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(733, 870)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 1, 1000, 300))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.imageFiltered = QtWidgets.QLabel(self.layoutWidget)
        self.imageFiltered.setText("")
        self.imageFiltered.setObjectName("imageFiltered")
        self.gridLayout.addWidget(self.imageFiltered, 2, 1, 1, 1)
        self.image = QtWidgets.QLabel(self.layoutWidget)
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.verticalLayoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget1.setGeometry(QtCore.QRect(20, 500, 361, 301))
        self.verticalLayoutWidget1.setObjectName("verticalLayoutWidget")
        self.tlLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget1)
        self.tlLayout.setObjectName("tlLayout")

        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(470, 580, 71, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon)
        self.playButton.setObjectName("playButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(560, 580, 71, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon1)
        self.stopButton.setObjectName("stopButton")
        self.takeoffButton = QtWidgets.QPushButton(self.centralwidget)
        self.takeoffButton.setGeometry(QtCore.QRect(470, 630, 161, 41))
        self.takeoffButton.setObjectName("takeoffButton")
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(470, 670, 161, 41))
        self.resetButton.setObjectName("resetButton")
        self.windowsLabel = QtWidgets.QLabel(self.centralwidget)
        self.windowsLabel.setGeometry(QtCore.QRect(540, 720, 71, 21))
        self.windowsLabel.setObjectName("windowsLabel")


        #self.cameraCheck = QtWidgets.QCheckBox(self.centralwidget)
        #self.cameraCheck.setGeometry(QtCore.QRect(540, 740, 94, 26))
        #self.cameraCheck.setObjectName("cameraCheck")
        self.sensorsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.sensorsCheck.setGeometry(QtCore.QRect(540, 760, 94, 26))
        self.sensorsCheck.setObjectName("sensorsCheck")


        self.XLabel = QtWidgets.QLabel(self.centralwidget)
        self.XLabel.setGeometry(QtCore.QRect(20, 800, 21, 21))
        self.XLabel.setObjectName("XLabel")
        self.YLabel = QtWidgets.QLabel(self.centralwidget)
        self.YLabel.setGeometry(QtCore.QRect(130, 800, 21, 21))
        self.YLabel.setObjectName("YLabel")
        self.XValue = QtWidgets.QLabel(self.centralwidget)
        self.XValue.setGeometry(QtCore.QRect(40, 800, 41, 21))
        self.XValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XValue.setObjectName("XValue")
        self.YValue = QtWidgets.QLabel(self.centralwidget)
        self.YValue.setGeometry(QtCore.QRect(150, 800, 41, 21))
        self.YValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YValue.setObjectName("YValue")
        self.altdSlider = QtWidgets.QSlider(self.centralwidget)
        self.altdSlider.setGeometry(QtCore.QRect(400, 520, 19, 311))
        self.altdSlider.setMaximum(100)
        self.altdSlider.setProperty("value", 49)
        self.altdSlider.setOrientation(QtCore.Qt.Vertical)
        self.altdSlider.setObjectName("altdSlider")
        self.altdLabel = QtWidgets.QLabel(self.centralwidget)
        self.altdLabel.setGeometry(QtCore.QRect(390, 830, 51, 21))
        self.altdLabel.setObjectName("altdLabel")
        self.rotationDial = QtWidgets.QDial(self.centralwidget)
        self.rotationDial.setGeometry(QtCore.QRect(440, 730, 50, 64))
        self.rotationDial.setMaximum(100)
        self.rotationDial.setProperty("value", 49)
        self.rotationDial.setObjectName("rotationDial")
        self.rotationLabel = QtWidgets.QLabel(self.centralwidget)
        self.rotationLabel.setGeometry(QtCore.QRect(440, 780, 65, 21))
        self.rotationLabel.setObjectName("rotationLabel")
        self.altdValue = QtWidgets.QLabel(self.centralwidget)
        self.altdValue.setGeometry(QtCore.QRect(390, 500, 41, 21))
        self.altdValue.setAlignment(QtCore.Qt.AlignCenter)
        self.altdValue.setObjectName("altdValue")
        self.rotValue = QtWidgets.QLabel(self.centralwidget)
        self.rotValue.setGeometry(QtCore.QRect(445, 720, 41, 21))
        self.rotValue.setAlignment(QtCore.Qt.AlignCenter)
        self.rotValue.setObjectName("rotValue")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Visual Lander"))

        self.playButton.setText(_translate("MainWindow", "Play Code"))
        self.stopButton.setText(_translate("MainWindow", "Stop Code"))
        self.takeoffButton.setText(_translate("MainWindow", "Take off"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.windowsLabel.setText(_translate("MainWindow", "Windows:"))
        self.sensorsCheck.setText(_translate("MainWindow", "Sensors"))
        self.altdLabel.setText(_translate("MainWindow", "Altitude"))
        self.rotationLabel.setText(_translate("MainWindow", "Rotation"))
        self.XLabel.setText(_translate("MainWindow", "X:"))
        self.YLabel.setText(_translate("MainWindow", "Y:"))
        self.XValue.setText(_translate("MainWindow", "0"))
        self.YValue.setText(_translate("MainWindow", "0"))
        self.altdValue.setText(_translate("MainWindow", "0"))
        self.rotValue.setText(_translate("MainWindow", "0"))

        self.image.setText(_translate("MainWindow", "Input_Image"))
        self.label.setText(_translate("MainWindow", "Camera Image"))
        self.label_2.setText(_translate("MainWindow", "Processed Image"))
        self.imageFiltered.setText(_translate("MainWindow", "Filtered_Image"))

import resources_rc
