--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.0 (Debian 17.0-1.pgdg120+1)

SET statement_timeout = 0;

SET lock_timeout = 0;

SET idle_in_transaction_session_timeout = 0;

SET transaction_timeout = 0;

SET client_encoding = 'UTF8';

SET standard_conforming_strings = on;

SELECT pg_catalog.set_config ('search_path', '', false);

SET check_function_bodies = false;

SET xmloption = content;

SET client_min_messages = warning;

SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: exercises; Type: TABLE; Schema: public; Owner: user-dev
--

CREATE TABLE public.exercises (
    id integer NOT NULL,
    exercise_id character varying (40) NOT NULL,
    name character varying (40) NOT NULL,
    description character varying (400) NOT NULL,
    tags character varying (2000) NOT NULL,
    entrypoints character varying (2000) NOT NULL,
    status character varying (20) NOT NULL,
    url character varying (200) NOT NULL
);

ALTER TABLE public.exercises OWNER TO "user-dev";

--
-- Name: exercises_id_seq; Type: SEQUENCE; Schema: public; Owner: user-dev
--

ALTER TABLE public.exercises ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: exercises_worlds; Type: TABLE; Schema: public; Owner: user-dev
--

CREATE TABLE public.exercises_worlds (
    id bigint NOT NULL,
    exercise_id bigint NOT NULL,
    world_id bigint NOT NULL,
    is_default BOOLEAN NOT NULL
);

ALTER TABLE public.exercises_worlds OWNER TO "user-dev";

--
-- Name: exercises_worlds_id_seq; Type: SEQUENCE; Schema: public; Owner: user-dev
--

ALTER TABLE public.exercises_worlds ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_worlds_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: exercises_tools; Type: TABLE; Schema: public; Owner: user-dev
--

CREATE TABLE public.exercises_tools (
    id bigint NOT NULL,
    exercise_id bigint NOT NULL,
    tool_id character varying (50) NOT NULL
);

ALTER TABLE public.exercises_tools OWNER TO "user-dev";

--
-- Name: exercises_tools_id_seq; Type: SEQUENCE; Schema: public; Owner: user-dev
--

ALTER TABLE public.exercises_tools ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_tools_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Data for Name: exercises; Type: TABLE DATA; Schema: public; Owner: user-dev
--


COPY public.exercises (id, exercise_id, name, description, tags, entrypoints, status, url) FROM stdin;
1	follow_line	Follow Line	The goal of this exercise is to perform a PID reactive control capable of following the line painted on the racing circuit.	["ROS2","AUTONOMOUS DRIVING", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/AutonomousCars/follow_line/
2	vacuum_cleaner	Basic Vacuum Cleaner	Basic Vacuum Cleaner exercise	["ROS2", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/MobileRobots/vacuum_cleaner
3	autoparking	Autoparking	Autoparking exercise testing	["AUTONOMOUS DRIVING", "SERVICE ROBOTS", "ROS2", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/AutonomousCars/autoparking
4	follow_person	Follow Person	Follow a person with kobuki robot	["ROS2", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/MobileRobots/follow_person
5	vacuum_cleaner_loc	Localized Vacuum Cleaner	Localiized vauum clenaer	["ROS2", "MOBILE ROBOTS", "SERVICE ROBOTS", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/MobileRobots/vacuum_cleaner_loc
6	global_navigation	Global Navigation	Global navigation exercise using REACT and RAM	["ROS2", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/AutonomousCars/global_navigation
7	rescue_people	Drone Rescue People	Drone Rescue People exercise	["ROS2", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/Drones/rescue_people
8	obstacle_avoidance	Obstacle Avoidance	Obstacle Avoidance exercise using React and RAM	["ROS2","AUTONOMOUS DRIVING",  "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/AutonomousCars/obstacle_avoidance
9	3d_reconstruction	3D Reconstruction	3D Reconstruction exercise using React and RAM	["ROS2","COMPUTER VISION", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/ComputerVision/3d_reconstruction
10	amazon_warehouse	Amazon Warehouse	Control an amazon-like robot to organize a warehouse	["ROS2", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/MobileRobots/amazon_warehouse
11	montecarlo_laser_loc	Montecarlo Laser Loc	Calculate the position of the robot based on the	["ROS2", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/MobileRobots/montecarlo_laser_loc
12	montecarlo_visual_loc	Montecarlo Visual Loc	Calculate the position of the robot based on the	["ROS2", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/ComputerVision/montecarlo_visual_loc
13	marker_visual_loc	Marker Visual Loc	Calculate the position of the robot based on the	["ROS2", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/ComputerVision/marker_visual_loc
14	laser_mapping	Laser Mapping	Build a map based on sensor readings	["ROS2", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/MobileRobots/laser_mapping
15	basic_computer_vision	Basic Computer Vision	Basic Computer Vision exercise using React and RAM	["ROS2", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/ComputerVision/basic_computer_vision
16	follow_road	Drone Follow Road	Drone Follow Road exercise	["ROS2", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/Drones/follow_road
17	pick_place	Pick and Place	Pick and Place exercise	["ROS2", "MULTILANGUAGE"]	[]	PROTOTYPE	https://jderobot.github.io/RoboticsAcademy/exercises/IndustrialRobots/pick_place
18	image_classification	Image Classification	Deep learning-based Image Classification.	["Computer Vision","Deep Learning","Classification", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/ComputerVision/image_classification
19	object_detection	Visual Object Detection	Deep learning-based object detection.	["Computer Vision","Deep Learning", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/ComputerVision/object_detection
20	drone_gymkhana	Drone Gymkhana	Drone Gymkhana	["ROS2", "Drones", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/Drones/drone_gymkhana
21	power_tower_inspection	Power Tower Inspection	Power Tower inspection using drones	["ROS2","Drones", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/Drones/power_tower_inspection
22	end_to_end_visual_control	End to End Visual Control	End to end visual control using deep learning.	["Computer Vision","Deep Learning","AUTONOMOUS DRIVING", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/AutonomousCars/end_to_end_visual_control
23	digital_image_processing	Digital Image Processing Exercises	Digital Image Processing Exercises	["ROS2"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/ComputerVision/digital_image_processing
24	car_junction	Car Junction	Autonomous Navigation through traffic at road junction.	["AUTONOMOUS DRIVING","ROS2", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/AutonomousCars/car_junction
25	machine_vision	Machine Vision	Machine Vision exercise	["ROS2", "MULTILANGUAGE"]	[]	PROTOTYPE	https://jderobot.github.io/RoboticsAcademy/exercises/IndustrialRobots/machine_vision
26	labyrinth_escape	Labyrinth Escape	Labyrinth Escape exercise	["ROS2","Drones", "MULTILANGUAGE"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/Drones/labyrinth_escape
27	conveyor_exercise	Conveyor Belt Exercise	Control a conveyor belt with ROS2	["ROS2","INDUSTRIAL"]	[]	PROTOTYPE	https://jderobot.github.io/RoboticsAcademy/exercises/IndustrialRobots/conveyor_exercise
28	drone_cat_mouse	Drone Cat Mouse	Two-drone chase exercise: program the cat drone to catch the mouse drone	["ROS2","Drones"]	["/resources/exercises/drone_cat_mouse/mouse.py"]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/Drones/drone_cat_mouse
29	package_delivery	Package Delivery	Drone Package Delivery exercise	["ROS2","Drones"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/Drones/package_delivery
30	drone_hangar	Drone Hangar	Escape a hangar filled with obstacles flying a drone	["ROS2","Drones"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/Drones/drone_hangar
31	position_control	Position Control	Fly a drone through a forest trail of beacons using a PID position controller	["ROS2","Drones"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/Drones/position_control
32	palletizing	Palletizing	Palletizing exercise	["ROS2", "MULTILANGUAGE"]	[]	PROTOTYPE	https://jderobot.github.io/RoboticsAcademy/exercises/IndustrialRobots/palletizing
33	visual_lander	Visual Lander	Visually track a moving car and land the drone on its color beacon	["ROS2","Drones"]	[]	ACTIVE	https://jderobot.github.io/RoboticsAcademy/exercises/Drones/visual_lander
\.

--
-- Data for Name: exercises_worlds; Type: TABLE DATA; Schema: public; Owner: user-dev
--


COPY public.exercises_worlds (id, exercise_id, world_id, is_default) FROM stdin;
1	2	1	True
2	5	1	True
4	7	31	False
6	1	5	False
7	1	6	False
11	11	1	True
13	9	12	True
21	1	20	False
22	1	21	False
23	1	22	False
24	1	23	False
25	1	24	False
26	1	25	False
27	12	27	False
28	13	29	False
29	14	30	False
30	16	32	False
31	14	33	False
33	22 	5	False
34	22	6	False
35	22	20	False
36	22	21	False
37	20	36	False
38	21	37	False
39	24	35	False
41	26	39	False
42	8	40	True
43	3	41	True
44	3	42	True
45	3	43	True
46	3	44	True
47	6	11	True
52	1	48	False
53	1	49	False
59	17	56	True
60	10	58	True
61	10	59	True
62	10	60	True
63	10	61	True
64	4	66	True
65	4	67	False
66	14	62	False
67	14	63	False
68	14	64	False
69	14	65	False
70	25	70	True
71	27	71	True
72	28	72	True
73	29	57	True
74	30	73	True
75	30	74	False
76	30	75	False
77	30	76	False
78	30	77	False
79	31	78	True
80	28	79	False
81	28	80	False
82	33	82	True
\.

--
-- Data for Name: exercises_tools; Type: TABLE DATA; Schema: public; Owner: user-dev
--


COPY public.exercises_tools (id, exercise_id, tool_id) FROM stdin;
1	1	console
2	1	simulator
3	1	web_gui
4	2	console
5	2	simulator
6	2	web_gui
7	3	console
8	3	simulator
9	3	web_gui
10	4	console
11	4	simulator
12	4	web_gui
13	5	console
14	5	simulator
15	5	web_gui
16	6	console
17	6	simulator
18	6	web_gui
19	7	console
20	7	simulator
21	7	web_gui
22	8	console
23	8	simulator
24	8	web_gui
25	9	console
26	9	simulator
27	9	web_gui
28	10	console
29	10	simulator
30	10	web_gui
31	11	console
32	11	simulator
33	11	web_gui
34	12	console
35	12	simulator
36	12	web_gui
37	13	console
38	13	simulator
39	13	web_gui
40	14	console
41	14	simulator
42	14	web_gui
43	15	console
44	15	webcam
45	15	web_gui
46	16	console
47	16	simulator
48	16	web_gui
49	17	console
50	17	simulator
51	18	console
52	18	webcam
53	18	web_gui
54	19	console
55	19	webcam
56	19	web_gui
57	20	web_gui
58	20	console
59	20	simulator
60	21	web_gui
61	21	console
62	21	simulator
63	22	console
64	22	simulator
65	22	web_gui
66	23	console
67	23	web_gui
68	24	web_gui
69	24	console
70	24	simulator
71	17	rviz
72	25	console
73	25	simulator
74	25	rviz
75	25	web_gui
76	26	console
77	26	simulator
78	26	web_gui
79	15	video
80	18	video
81	19	video
82	27	simulator
83	27	console
84	27	rviz
85	27	web_gui
86	28	console
87	28	simulator
88	28	web_gui
89	29	console
90	29	simulator
91	29	web_gui
92	30	console
93	30	simulator
94	30	web_gui
95	31	console
96	31	simulator
97	31	web_gui
98	32	console
99	32	simulator
100	32	rviz
101	33	console
102	33	simulator
103	33	web_gui
\.

--
-- Name: exercises_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user-dev
--

SELECT pg_catalog.setval ( 'public.exercises_id_seq', 1, false );

--
-- Name: exercises_worlds_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user-dev
--

SELECT pg_catalog.setval (
        'public.exercises_worlds_id_seq', 1, false
    );

--
-- Name: exercises_tools_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user-dev
--

SELECT pg_catalog.setval (
        'public.exercises_tools_id_seq', 1, false
    );

--
-- Name: exercises exercises_exercise_id_key; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.exercises
ADD CONSTRAINT exercises_exercise_id_key UNIQUE (exercise_id);

--
-- Name: exercises exercises_name_key; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.exercises
ADD CONSTRAINT exercises_name_key UNIQUE (name);

--
-- Name: exercises exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.exercises
ADD CONSTRAINT exercises_pkey PRIMARY KEY (id);

--
-- Name: exercises_worlds exercises_worlds_exercise_id_world_id_155bee4e_uniq; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.exercises_worlds
ADD CONSTRAINT exercises_worlds_exercise_id_world_id_155bee4e_uniq UNIQUE (exercise_id, world_id);

--
-- Name: exercises_worlds exercises_worlds_pkey; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.exercises_worlds
ADD CONSTRAINT exercises_worlds_pkey PRIMARY KEY (id);

--
-- Name: exercises_tools exercises_tools_exercise_id_world_id_155bee4e_uniq; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.exercises_tools
ADD CONSTRAINT exercises_tools_exercise_id_tool_id_155bee4e_uniq UNIQUE (exercise_id, tool_id);

--
-- Name: exercises_tools exercises_tools_pkey; Type: CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.exercises_tools
ADD CONSTRAINT exercises_tools_pkey PRIMARY KEY (id);

--
-- Name: exercises_exercise_id_c21d158f_like; Type: INDEX; Schema: public; Owner: user-dev
--

CREATE INDEX exercises_exercise_id_c21d158f_like ON public.exercises USING btree (
    exercise_id varchar_pattern_ops
);

--
-- Name: exercises_name_d52987aa_like; Type: INDEX; Schema: public; Owner: user-dev
--

CREATE INDEX exercises_name_d52987aa_like ON public.exercises USING btree (name varchar_pattern_ops);

--
-- Name: exercises_worlds_exercise_id_e4e984bc; Type: INDEX; Schema: public; Owner: user-dev
--

CREATE INDEX exercises_worlds_exercise_id_e4e984bc ON public.exercises_worlds USING btree (exercise_id);

--
-- Name: exercises_worlds_world_id_13c30e27; Type: INDEX; Schema: public; Owner: user-dev
--

CREATE INDEX exercises_worlds_world_id_13c30e27 ON public.exercises_worlds USING btree (world_id);

--
-- Name: exercises_worlds exercises_worlds_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.exercises_worlds
ADD CONSTRAINT exercises_worlds_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises (id);

--
-- Name: exercises_worlds exercises_w_exercise_id_e4e984bc_fk_exercises; Type: FK CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.exercises_worlds
ADD CONSTRAINT exercises_w_exercise_id_e4e984bc_fk_exercises FOREIGN KEY (exercise_id) REFERENCES public.exercises (id) DEFERRABLE INITIALLY DEFERRED;

--
-- Name: exercises_tools_exercise_id_e4e984bc; Type: INDEX; Schema: public; Owner: user-dev
--

CREATE INDEX exercises_tools_exercise_id_e4e984bc ON public.exercises_tools USING btree (exercise_id);

--
-- Name: exercises_tools_world_id_13c30e27; Type: INDEX; Schema: public; Owner: user-dev
--

CREATE INDEX exercises_tools_world_id_13c30e27 ON public.exercises_tools USING btree (tool_id);

--
-- Name: exercises_tools exercises_tools_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.exercises_tools
ADD CONSTRAINT exercises_tools_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises (id);

--
-- Name: exercises_tools exercises_w_exercise_id_e4e984bc_fk_exercises; Type: FK CONSTRAINT; Schema: public; Owner: user-dev
--

ALTER TABLE ONLY public.exercises_tools
ADD CONSTRAINT exercises_w_exercise_id_e4e984bc_fk_exercises FOREIGN KEY (exercise_id) REFERENCES public.exercises (id) DEFERRABLE INITIALLY DEFERRED;

--
-- PostgreSQL database dump complete
--