version: '3.8'

services:
  my-postgres:
    image: postgres:latest
    container_name: universe_db
    environment:
      POSTGRES_DB: academy_db 
      POSTGRES_USER: user-dev 
      POSTGRES_PASSWORD: robotics-academy-dev

  robotics-academy:
    image: jderobot/robotics-backend:test
    container_name: developer-container
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - "7164:7164"
      - "7163:7163"
      - "6080:6080"
      - "1108:1108"
      - "5432:5432"
    volumes:
      - type: bind
        source: ./
        target: /RoboticsAcademy
    tty: true
    stdin_open: true
    depends_on: 
      - my-postgres