version: '3.8'

services:
  robotics-academy:
    image: jderobot/robotics-backend:latest
    container_name: developer-container
    ports:
      - "7164:7164"
      - "7163:7163"
      - "6080:6080"
      - "1108:1108"
    volumes:
      - type: bind
        source: ./
        target: /RoboticsAcademy
    tty: true
    stdin_open: true
