version: '3.8'

services:
  robotics-academy:
    image: jderobot/robotics-academy:4.5.11
    container_name: user_container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # devices:
    #   - /dev/dri/card0:/dev/dri/card0
    #   - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - "7164:7164"
      - "6080:6080"
      - "1108:1108"
      - "7163:7163"
    tty: true
    stdin_open: true
