# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'colorFilter.ui'
#
# Created: Thu Jun  4 14:33:52 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(900, 580)
        Form.setMinimumSize(QtCore.QSize(900, 580))
        Form.setMaximumSize(QtCore.QSize(900, 580))
        self.inputImage = QtGui.QLabel(Form)
        self.inputImage.setGeometry(QtCore.QRect(80, 50, 320, 240))
        self.inputImage.setMinimumSize(QtCore.QSize(320, 240))
        self.inputImage.setMaximumSize(QtCore.QSize(320, 240))
        self.inputImage.setObjectName(_fromUtf8("inputImage"))
        self.outputFilterImage = QtGui.QLabel(Form)
        self.outputFilterImage.setGeometry(QtCore.QRect(500, 50, 320, 240))
        self.outputFilterImage.setMinimumSize(QtCore.QSize(320, 240))
        self.outputFilterImage.setMaximumSize(QtCore.QSize(320, 240))
        self.outputFilterImage.setObjectName(_fromUtf8("outputFilterImage"))
        self.slidersBox = QtGui.QGroupBox(Form)
        self.slidersBox.setGeometry(QtCore.QRect(210, 290, 460, 200))
        self.slidersBox.setMinimumSize(QtCore.QSize(460, 200))
        self.slidersBox.setMaximumSize(QtCore.QSize(460, 200))
        self.slidersBox.setTitle(_fromUtf8(""))
        self.slidersBox.setObjectName(_fromUtf8("slidersBox"))
        self.hminSlider = QtGui.QSlider(self.slidersBox)
        self.hminSlider.setGeometry(QtCore.QRect(90, 20, 280, 20))
        self.hminSlider.setMinimumSize(QtCore.QSize(280, 20))
        self.hminSlider.setMaximumSize(QtCore.QSize(280, 20))
        self.hminSlider.setMaximum(180)
        self.hminSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hminSlider.setObjectName(_fromUtf8("hminSlider"))
        self.hminLabel = QtGui.QLabel(self.slidersBox)
        self.hminLabel.setGeometry(QtCore.QRect(30, 20, 65, 21))
        self.hminLabel.setMinimumSize(QtCore.QSize(65, 21))
        self.hminLabel.setMaximumSize(QtCore.QSize(65, 21))
        self.hminLabel.setObjectName(_fromUtf8("hminLabel"))
        self.hminValue = QtGui.QLabel(self.slidersBox)
        self.hminValue.setGeometry(QtCore.QRect(390, 20, 65, 21))
        self.hminValue.setMinimumSize(QtCore.QSize(65, 21))
        self.hminValue.setMaximumSize(QtCore.QSize(65, 21))
        self.hminValue.setObjectName(_fromUtf8("hminValue"))
        self.hmaxLabel = QtGui.QLabel(self.slidersBox)
        self.hmaxLabel.setGeometry(QtCore.QRect(30, 50, 65, 21))
        self.hmaxLabel.setMinimumSize(QtCore.QSize(65, 21))
        self.hmaxLabel.setMaximumSize(QtCore.QSize(65, 21))
        self.hmaxLabel.setObjectName(_fromUtf8("hmaxLabel"))
        self.hmaxValue = QtGui.QLabel(self.slidersBox)
        self.hmaxValue.setGeometry(QtCore.QRect(390, 50, 65, 21))
        self.hmaxValue.setMinimumSize(QtCore.QSize(65, 21))
        self.hmaxValue.setMaximumSize(QtCore.QSize(65, 21))
        self.hmaxValue.setObjectName(_fromUtf8("hmaxValue"))
        self.hmaxSlider = QtGui.QSlider(self.slidersBox)
        self.hmaxSlider.setGeometry(QtCore.QRect(90, 50, 280, 20))
        self.hmaxSlider.setMinimumSize(QtCore.QSize(280, 20))
        self.hmaxSlider.setMaximumSize(QtCore.QSize(280, 20))
        self.hmaxSlider.setMaximum(180)
        self.hmaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hmaxSlider.setObjectName(_fromUtf8("hmaxSlider"))
        self.sminLabel = QtGui.QLabel(self.slidersBox)
        self.sminLabel.setGeometry(QtCore.QRect(30, 80, 65, 21))
        self.sminLabel.setMinimumSize(QtCore.QSize(65, 21))
        self.sminLabel.setMaximumSize(QtCore.QSize(65, 21))
        self.sminLabel.setObjectName(_fromUtf8("sminLabel"))
        self.sminValue = QtGui.QLabel(self.slidersBox)
        self.sminValue.setGeometry(QtCore.QRect(390, 80, 65, 21))
        self.sminValue.setMinimumSize(QtCore.QSize(65, 21))
        self.sminValue.setMaximumSize(QtCore.QSize(65, 21))
        self.sminValue.setObjectName(_fromUtf8("sminValue"))
        self.sminSlider = QtGui.QSlider(self.slidersBox)
        self.sminSlider.setGeometry(QtCore.QRect(90, 80, 280, 20))
        self.sminSlider.setMinimumSize(QtCore.QSize(280, 20))
        self.sminSlider.setMaximumSize(QtCore.QSize(280, 20))
        self.sminSlider.setMaximum(255)
        self.sminSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sminSlider.setObjectName(_fromUtf8("sminSlider"))
        self.smaxLabel = QtGui.QLabel(self.slidersBox)
        self.smaxLabel.setGeometry(QtCore.QRect(30, 110, 65, 21))
        self.smaxLabel.setMinimumSize(QtCore.QSize(65, 21))
        self.smaxLabel.setMaximumSize(QtCore.QSize(65, 21))
        self.smaxLabel.setObjectName(_fromUtf8("smaxLabel"))
        self.smaxValue = QtGui.QLabel(self.slidersBox)
        self.smaxValue.setGeometry(QtCore.QRect(390, 110, 65, 21))
        self.smaxValue.setMinimumSize(QtCore.QSize(65, 21))
        self.smaxValue.setMaximumSize(QtCore.QSize(65, 21))
        self.smaxValue.setObjectName(_fromUtf8("smaxValue"))
        self.smaxSlider = QtGui.QSlider(self.slidersBox)
        self.smaxSlider.setGeometry(QtCore.QRect(90, 110, 280, 20))
        self.smaxSlider.setMinimumSize(QtCore.QSize(280, 20))
        self.smaxSlider.setMaximumSize(QtCore.QSize(280, 20))
        self.smaxSlider.setMaximum(255)
        self.smaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.smaxSlider.setObjectName(_fromUtf8("smaxSlider"))
        self.vminLabel = QtGui.QLabel(self.slidersBox)
        self.vminLabel.setGeometry(QtCore.QRect(30, 140, 65, 21))
        self.vminLabel.setMinimumSize(QtCore.QSize(65, 21))
        self.vminLabel.setMaximumSize(QtCore.QSize(65, 21))
        self.vminLabel.setObjectName(_fromUtf8("vminLabel"))
        self.vminValue = QtGui.QLabel(self.slidersBox)
        self.vminValue.setGeometry(QtCore.QRect(390, 140, 65, 21))
        self.vminValue.setMinimumSize(QtCore.QSize(65, 21))
        self.vminValue.setMaximumSize(QtCore.QSize(65, 21))
        self.vminValue.setObjectName(_fromUtf8("vminValue"))
        self.vminSlider = QtGui.QSlider(self.slidersBox)
        self.vminSlider.setGeometry(QtCore.QRect(90, 140, 280, 20))
        self.vminSlider.setMinimumSize(QtCore.QSize(280, 20))
        self.vminSlider.setMaximumSize(QtCore.QSize(280, 20))
        self.vminSlider.setMaximum(255)
        self.vminSlider.setOrientation(QtCore.Qt.Horizontal)
        self.vminSlider.setObjectName(_fromUtf8("vminSlider"))
        self.vmaxLabel = QtGui.QLabel(self.slidersBox)
        self.vmaxLabel.setGeometry(QtCore.QRect(30, 170, 65, 21))
        self.vmaxLabel.setMinimumSize(QtCore.QSize(65, 21))
        self.vmaxLabel.setMaximumSize(QtCore.QSize(65, 21))
        self.vmaxLabel.setObjectName(_fromUtf8("vmaxLabel"))
        self.vmaxValue = QtGui.QLabel(self.slidersBox)
        self.vmaxValue.setGeometry(QtCore.QRect(390, 170, 65, 21))
        self.vmaxValue.setMinimumSize(QtCore.QSize(65, 21))
        self.vmaxValue.setMaximumSize(QtCore.QSize(65, 21))
        self.vmaxValue.setObjectName(_fromUtf8("vmaxValue"))
        self.vmaxSlider = QtGui.QSlider(self.slidersBox)
        self.vmaxSlider.setGeometry(QtCore.QRect(90, 170, 280, 20))
        self.vmaxSlider.setMinimumSize(QtCore.QSize(280, 20))
        self.vmaxSlider.setMaximumSize(QtCore.QSize(280, 20))
        self.vmaxSlider.setMaximum(255)
        self.vmaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.vmaxSlider.setObjectName(_fromUtf8("vmaxSlider"))
        self.inputImageLabel = QtGui.QLabel(Form)
        self.inputImageLabel.setGeometry(QtCore.QRect(80, 30, 81, 21))
        self.inputImageLabel.setObjectName(_fromUtf8("inputImageLabel"))
        self.filterOutputLabel = QtGui.QLabel(Form)
        self.filterOutputLabel.setGeometry(QtCore.QRect(500, 30, 91, 21))
        self.filterOutputLabel.setObjectName(_fromUtf8("filterOutputLabel"))
        self.resetButton = QtGui.QPushButton(Form)
        self.resetButton.setGeometry(QtCore.QRect(280, 520, 96, 31))
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.trackButton = QtGui.QPushButton(Form)
        self.trackButton.setGeometry(QtCore.QRect(490, 520, 96, 31))
        self.trackButton.setObjectName(_fromUtf8("trackButton"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Color Filter", None))
        self.inputImage.setText(_translate("Form", "TextLabel", None))
        self.outputFilterImage.setText(_translate("Form", "TextLabel", None))
        self.hminLabel.setText(_translate("Form", "H min", None))
        self.hminValue.setText(_translate("Form", "0", None))
        self.hmaxLabel.setText(_translate("Form", "H max", None))
        self.hmaxValue.setText(_translate("Form", "0", None))
        self.sminLabel.setText(_translate("Form", "S min", None))
        self.sminValue.setText(_translate("Form", "0", None))
        self.smaxLabel.setText(_translate("Form", "S max", None))
        self.smaxValue.setText(_translate("Form", "0", None))
        self.vminLabel.setText(_translate("Form", "V min", None))
        self.vminValue.setText(_translate("Form", "0", None))
        self.vmaxLabel.setText(_translate("Form", "V max", None))
        self.vmaxValue.setText(_translate("Form", "0", None))
        self.inputImageLabel.setText(_translate("Form", "Input image:", None))
        self.filterOutputLabel.setText(_translate("Form", "Filter output:", None))
        self.resetButton.setText(_translate("Form", "Reset values", None))
        self.trackButton.setText(_translate("Form", "Track", None))

