# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'colorFilter.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 580)
        Form.setMinimumSize(QtCore.QSize(900, 580))
        Form.setMaximumSize(QtCore.QSize(900, 580))
        self.inputImage = QtWidgets.QLabel(Form)
        self.inputImage.setGeometry(QtCore.QRect(80, 50, 320, 240))
        self.inputImage.setMinimumSize(QtCore.QSize(320, 240))
        self.inputImage.setMaximumSize(QtCore.QSize(320, 240))
        self.inputImage.setObjectName("inputImage")
        self.outputFilterImage = QtWidgets.QLabel(Form)
        self.outputFilterImage.setGeometry(QtCore.QRect(500, 50, 320, 240))
        self.outputFilterImage.setMinimumSize(QtCore.QSize(320, 240))
        self.outputFilterImage.setMaximumSize(QtCore.QSize(320, 240))
        self.outputFilterImage.setObjectName("outputFilterImage")
        self.slidersBox = QtWidgets.QGroupBox(Form)
        self.slidersBox.setGeometry(QtCore.QRect(210, 290, 460, 200))
        self.slidersBox.setMinimumSize(QtCore.QSize(460, 200))
        self.slidersBox.setMaximumSize(QtCore.QSize(460, 200))
        self.slidersBox.setTitle("")
        self.slidersBox.setObjectName("slidersBox")
        self.hminSlider = QtWidgets.QSlider(self.slidersBox)
        self.hminSlider.setGeometry(QtCore.QRect(90, 20, 280, 20))
        self.hminSlider.setMinimumSize(QtCore.QSize(280, 20))
        self.hminSlider.setMaximumSize(QtCore.QSize(280, 20))
        self.hminSlider.setMaximum(180)
        self.hminSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hminSlider.setObjectName("hminSlider")
        self.hminLabel = QtWidgets.QLabel(self.slidersBox)
        self.hminLabel.setGeometry(QtCore.QRect(30, 20, 65, 21))
        self.hminLabel.setMinimumSize(QtCore.QSize(65, 21))
        self.hminLabel.setMaximumSize(QtCore.QSize(65, 21))
        self.hminLabel.setObjectName("hminLabel")
        self.hminValue = QtWidgets.QLabel(self.slidersBox)
        self.hminValue.setGeometry(QtCore.QRect(390, 20, 65, 21))
        self.hminValue.setMinimumSize(QtCore.QSize(65, 21))
        self.hminValue.setMaximumSize(QtCore.QSize(65, 21))
        self.hminValue.setObjectName("hminValue")
        self.hmaxLabel = QtWidgets.QLabel(self.slidersBox)
        self.hmaxLabel.setGeometry(QtCore.QRect(30, 50, 65, 21))
        self.hmaxLabel.setMinimumSize(QtCore.QSize(65, 21))
        self.hmaxLabel.setMaximumSize(QtCore.QSize(65, 21))
        self.hmaxLabel.setObjectName("hmaxLabel")
        self.hmaxValue = QtWidgets.QLabel(self.slidersBox)
        self.hmaxValue.setGeometry(QtCore.QRect(390, 50, 65, 21))
        self.hmaxValue.setMinimumSize(QtCore.QSize(65, 21))
        self.hmaxValue.setMaximumSize(QtCore.QSize(65, 21))
        self.hmaxValue.setObjectName("hmaxValue")
        self.hmaxSlider = QtWidgets.QSlider(self.slidersBox)
        self.hmaxSlider.setGeometry(QtCore.QRect(90, 50, 280, 20))
        self.hmaxSlider.setMinimumSize(QtCore.QSize(280, 20))
        self.hmaxSlider.setMaximumSize(QtCore.QSize(280, 20))
        self.hmaxSlider.setMaximum(180)
        self.hmaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hmaxSlider.setObjectName("hmaxSlider")
        self.sminLabel = QtWidgets.QLabel(self.slidersBox)
        self.sminLabel.setGeometry(QtCore.QRect(30, 80, 65, 21))
        self.sminLabel.setMinimumSize(QtCore.QSize(65, 21))
        self.sminLabel.setMaximumSize(QtCore.QSize(65, 21))
        self.sminLabel.setObjectName("sminLabel")
        self.sminValue = QtWidgets.QLabel(self.slidersBox)
        self.sminValue.setGeometry(QtCore.QRect(390, 80, 65, 21))
        self.sminValue.setMinimumSize(QtCore.QSize(65, 21))
        self.sminValue.setMaximumSize(QtCore.QSize(65, 21))
        self.sminValue.setObjectName("sminValue")
        self.sminSlider = QtWidgets.QSlider(self.slidersBox)
        self.sminSlider.setGeometry(QtCore.QRect(90, 80, 280, 20))
        self.sminSlider.setMinimumSize(QtCore.QSize(280, 20))
        self.sminSlider.setMaximumSize(QtCore.QSize(280, 20))
        self.sminSlider.setMaximum(255)
        self.sminSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sminSlider.setObjectName("sminSlider")
        self.smaxLabel = QtWidgets.QLabel(self.slidersBox)
        self.smaxLabel.setGeometry(QtCore.QRect(30, 110, 65, 21))
        self.smaxLabel.setMinimumSize(QtCore.QSize(65, 21))
        self.smaxLabel.setMaximumSize(QtCore.QSize(65, 21))
        self.smaxLabel.setObjectName("smaxLabel")
        self.smaxValue = QtWidgets.QLabel(self.slidersBox)
        self.smaxValue.setGeometry(QtCore.QRect(390, 110, 65, 21))
        self.smaxValue.setMinimumSize(QtCore.QSize(65, 21))
        self.smaxValue.setMaximumSize(QtCore.QSize(65, 21))
        self.smaxValue.setObjectName("smaxValue")
        self.smaxSlider = QtWidgets.QSlider(self.slidersBox)
        self.smaxSlider.setGeometry(QtCore.QRect(90, 110, 280, 20))
        self.smaxSlider.setMinimumSize(QtCore.QSize(280, 20))
        self.smaxSlider.setMaximumSize(QtCore.QSize(280, 20))
        self.smaxSlider.setMaximum(255)
        self.smaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.smaxSlider.setObjectName("smaxSlider")
        self.vminLabel = QtWidgets.QLabel(self.slidersBox)
        self.vminLabel.setGeometry(QtCore.QRect(30, 140, 65, 21))
        self.vminLabel.setMinimumSize(QtCore.QSize(65, 21))
        self.vminLabel.setMaximumSize(QtCore.QSize(65, 21))
        self.vminLabel.setObjectName("vminLabel")
        self.vminValue = QtWidgets.QLabel(self.slidersBox)
        self.vminValue.setGeometry(QtCore.QRect(390, 140, 65, 21))
        self.vminValue.setMinimumSize(QtCore.QSize(65, 21))
        self.vminValue.setMaximumSize(QtCore.QSize(65, 21))
        self.vminValue.setObjectName("vminValue")
        self.vminSlider = QtWidgets.QSlider(self.slidersBox)
        self.vminSlider.setGeometry(QtCore.QRect(90, 140, 280, 20))
        self.vminSlider.setMinimumSize(QtCore.QSize(280, 20))
        self.vminSlider.setMaximumSize(QtCore.QSize(280, 20))
        self.vminSlider.setMaximum(255)
        self.vminSlider.setOrientation(QtCore.Qt.Horizontal)
        self.vminSlider.setObjectName("vminSlider")
        self.vmaxLabel = QtWidgets.QLabel(self.slidersBox)
        self.vmaxLabel.setGeometry(QtCore.QRect(30, 170, 65, 21))
        self.vmaxLabel.setMinimumSize(QtCore.QSize(65, 21))
        self.vmaxLabel.setMaximumSize(QtCore.QSize(65, 21))
        self.vmaxLabel.setObjectName("vmaxLabel")
        self.vmaxValue = QtWidgets.QLabel(self.slidersBox)
        self.vmaxValue.setGeometry(QtCore.QRect(390, 170, 65, 21))
        self.vmaxValue.setMinimumSize(QtCore.QSize(65, 21))
        self.vmaxValue.setMaximumSize(QtCore.QSize(65, 21))
        self.vmaxValue.setObjectName("vmaxValue")
        self.vmaxSlider = QtWidgets.QSlider(self.slidersBox)
        self.vmaxSlider.setGeometry(QtCore.QRect(90, 170, 280, 20))
        self.vmaxSlider.setMinimumSize(QtCore.QSize(280, 20))
        self.vmaxSlider.setMaximumSize(QtCore.QSize(280, 20))
        self.vmaxSlider.setMaximum(255)
        self.vmaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.vmaxSlider.setObjectName("vmaxSlider")
        self.inputImageLabel = QtWidgets.QLabel(Form)
        self.inputImageLabel.setGeometry(QtCore.QRect(80, 30, 81, 21))
        self.inputImageLabel.setObjectName("inputImageLabel")
        self.filterOutputLabel = QtWidgets.QLabel(Form)
        self.filterOutputLabel.setGeometry(QtCore.QRect(500, 30, 91, 21))
        self.filterOutputLabel.setObjectName("filterOutputLabel")
        self.resetButton = QtWidgets.QPushButton(Form)
        self.resetButton.setGeometry(QtCore.QRect(280, 520, 96, 31))
        self.resetButton.setObjectName("resetButton")
        self.trackButton = QtWidgets.QPushButton(Form)
        self.trackButton.setGeometry(QtCore.QRect(490, 520, 96, 31))
        self.trackButton.setObjectName("trackButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Color Filter"))
        self.inputImage.setText(_translate("Form", "TextLabel"))
        self.outputFilterImage.setText(_translate("Form", "TextLabel"))
        self.hminLabel.setText(_translate("Form", "H min"))
        self.hminValue.setText(_translate("Form", "0"))
        self.hmaxLabel.setText(_translate("Form", "H max"))
        self.hmaxValue.setText(_translate("Form", "0"))
        self.sminLabel.setText(_translate("Form", "S min"))
        self.sminValue.setText(_translate("Form", "0"))
        self.smaxLabel.setText(_translate("Form", "S max"))
        self.smaxValue.setText(_translate("Form", "0"))
        self.vminLabel.setText(_translate("Form", "V min"))
        self.vminValue.setText(_translate("Form", "0"))
        self.vmaxLabel.setText(_translate("Form", "V max"))
        self.vmaxValue.setText(_translate("Form", "0"))
        self.inputImageLabel.setText(_translate("Form", "Input image:"))
        self.filterOutputLabel.setText(_translate("Form", "Filter output:"))
        self.resetButton.setText(_translate("Form", "Reset values"))
        self.trackButton.setText(_translate("Form", "Track"))

