// This helps us get the url of the Theory of the Exercise
const BaseUrl = "https://jderobot.github.io/RoboticsAcademy/exercises/";
export const THEORY_URL = {
  FollowLine: BaseUrl + "AutonomousCars/follow_line/",
  AutoParking: BaseUrl + "AutonomousCars/autoparking/",
  CarJunction: BaseUrl + "AutonomousCars/car_junction/",
  RoadJunction: BaseUrl + "AutonomousCars/car_junction/",
  GlobalNavigation: BaseUrl + "AutonomousCars/global_navigation/",
  ObstacleAvoidance: BaseUrl + "AutonomousCars/obstacle_avoidance",
  ColorFilter: BaseUrl + "ComputerVision/color_filter",
  HumanDetection: BaseUrl + "ComputerVision/human_detection",
  OpticalFlowTeleOp: BaseUrl + "ComputerVision/opticalflow_teleop/",
  _3dReconstruction: BaseUrl + "ComputerVision/3d_reconstruction",
  DlDigitClassifier: BaseUrl + "ComputerVision/dl_digit_classifier",
  MonteCarloVisualLoc: BaseUrl + "ComputerVision/montecarlo_visual_loc",
  DroneCatMouse: BaseUrl + "Drones/drone_cat_mouse",
  DroneGymKhana: BaseUrl + "Drones/drone_gymkhana",
  DroneHanger: BaseUrl + "Drones/drone_hangar",
  FollowRoad: BaseUrl + "Drones/follow_road",
  PowerTowerInspection: BaseUrl + "Drones/power_tower_inspection",
  PackageDelivery: BaseUrl + "Drones/package_delivery",
  VisualLander: BaseUrl + "Drones/visual_lander",
  FollowTurtleBot: BaseUrl + "Drones/follow_turtlebot",
  LabyrinthEscape: BaseUrl + "Drones/labyrinth_escape",
  PositionControl: BaseUrl + "Drones/position_control",
  RescuePeople: BaseUrl + "Drones/rescue_people",
  LaserLoc: BaseUrl + "MobileRobots/laser_loc/",
  LaserMapping: BaseUrl + "MobileRobots/laser_mapping",
  VacuumCleaner: BaseUrl + "MobileRobots/vacuum_cleaner",
  VacuumCleanerLoc: BaseUrl + "MobileRobots/vacuum_cleaner_loc",
};
