# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1347, 904)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/jderobot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 680, 171, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.logoLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.logoLayout.setContentsMargins(0, 0, 0, 0)
        self.logoLayout.setObjectName("logoLayout")
        self.playpause = QtWidgets.QPushButton(self.centralwidget)
        self.playpause.setGeometry(QtCore.QRect(260, 300, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.playpause.setFont(font)
        self.playpause.setCheckable(True)
        self.playpause.setChecked(False)
        self.playpause.setObjectName("playpause")
        self.plot = PlotWidget(self.centralwidget)
        self.plot.setGeometry(QtCore.QRect(710, 30, 621, 571))
        self.plot.setObjectName("plot")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(740, 680, 541, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.orig_img = QtWidgets.QLabel(self.centralwidget)
        self.orig_img.setGeometry(QtCore.QRect(40, 30, 320, 240))
        self.orig_img.setObjectName("orig_img")
        self.processed_img = QtWidgets.QLabel(self.centralwidget)
        self.processed_img.setGeometry(QtCore.QRect(380, 30, 320, 240))
        self.processed_img.setObjectName("processed_img")
        self.mean = QtWidgets.QLCDNumber(self.centralwidget)
        self.mean.setGeometry(QtCore.QRect(190, 430, 141, 51))
        self.mean.setObjectName("mean")
        self.median = QtWidgets.QLCDNumber(self.centralwidget)
        self.median.setGeometry(QtCore.QRect(190, 500, 141, 51))
        self.median.setObjectName("median")
        self.Std_dev = QtWidgets.QLCDNumber(self.centralwidget)
        self.Std_dev.setGeometry(QtCore.QRect(190, 580, 141, 51))
        self.Std_dev.setObjectName("Std_dev")
        self.rmse = QtWidgets.QLCDNumber(self.centralwidget)
        self.rmse.setGeometry(QtCore.QRect(530, 430, 141, 51))
        self.rmse.setObjectName("rmse")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 380, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 440, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 510, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 590, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(400, 440, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(570, 680, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.realtime = QtWidgets.QLCDNumber(self.centralwidget)
        self.realtime.setGeometry(QtCore.QRect(530, 530, 141, 51))
        self.realtime.setObjectName("realtime")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(370, 540, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(350, 500, 361, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-10, 360, 721, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(342, 510, 21, 161))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(-3, 660, 361, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(350, 590, 361, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(120, 0, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(440, 0, 181, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1347, 32))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Visual Odometry"))
        self.playpause.setText(_translate("MainWindow", "Play Code"))
        self.orig_img.setText(_translate("MainWindow", "TextLabel"))
        self.processed_img.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "Absolute Translational Error"))
        self.label_3.setText(_translate("MainWindow", "MEAN:-"))
        self.label_4.setText(_translate("MainWindow", "MEDIAN:-"))
        self.label_5.setText(_translate("MainWindow", "Std. DEVIATION:-"))
        self.label_6.setText(_translate("MainWindow", "RMSE:-"))
        self.label_7.setText(_translate("MainWindow", "Progress:-"))
        self.label_8.setText(_translate("MainWindow", "RT Factor:-"))
        self.label_9.setText(_translate("MainWindow", "RGB Image"))
        self.label_10.setText(_translate("MainWindow", "Processed image"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

from plotWidget import PlotWidget
import resources_rc
