import React, { lazy, ReactNode } from "react";
import "./exercise-index.css";
import { createRoot } from "react-dom/client";
import "./libs/tools.js";
import { flushSync } from "react-dom";
import "./styles/tailwindcss_base.css";

declare global {
  interface Window {
    ExerciseRenderer: Function;
  }
}

window.ExerciseRenderer = function (rootRenderer: Object) {
  let components = [];

  /**
   * Creates a DOM element and include their children
   * @param element
   * @returns {*}
   */
  const createElement = function (element: any): ReactNode {
    const children: ReactNode = Array.from(element.childNodes).map(
      (child: any) => createElement(child)
    );
    return React.createElement(element, {}, children);
  };

  /**
   * Renders a React component in runtime
   * @param component Component to trender
   * @param container_id Container id of the component container
   * @param properties Properties to add to the component
   * @param children_elements Child elements
   * @returns {React.DetailedReactHTMLElement<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>}
   */
  const renderComponentNew = function (
    component: any,
    container_id: any,
    properties: any,
    children_elements: any
  ) {
    const container = document.getElementById(container_id);
    properties["key"] = container_id;
    let element = React.createElement(component, properties, children_elements);
    components.push(element);
    return element;
  };

  /**
   * Renders a react element generated by a django template {% tag react_component %}
   * @param element Element description object
   * @returns {Promise<{}>}
   */
  const renderImportNew = async function (
    element: any,
    parent_is_root: boolean
  ): Promise<ReactNode> {
    const { component, dom_id, properties, children } = element;

    const is_root = component === "root";

    // Process children first
    const child_elements = await Promise.all(
      children.map(async (child: any) => {
        return await renderImportNew(child, is_root);
      })
    );

    const path = component.split("/");
    let rendered_component: ReactNode;

    if (is_root) return rendered_component;

    if (path[0] === "exercise") {
      const component_path = `${path.slice(1).join("/")}.js`;
      console.log(component_path)
      rendered_component = await import(`exercises/${component_path}`).then(
        (component) => {
          return renderComponentNew(
            component.default,
            dom_id,
            properties,
            child_elements
          );
        }
      );
    } else {
      rendered_component = await import(`/${component}`).then((component) => {
        return renderComponentNew(
          component.default,
          dom_id,
          properties,
          child_elements
        );
      });
    }

    if (parent_is_root) {
      const element = document.getElementById(dom_id);
      const root = createRoot(element!);
      flushSync(() => {
        root.render(rendered_component);
      });
    }

    return rendered_component;
  };

  const render = async function (rootRenderer: Object) {
    await renderImportNew(rootRenderer, false);
  };

  render(rootRenderer);
};
