# Generated by Django 3.2 on 2021-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('testing', 'Testing')], max_length=40)),
                ('platform', models.CharField(blank=True, choices=[('gazebo', 'Gazebo'), ('real', 'Real'), ('theory', 'Theory'), ('vision', 'Vision'), ('tutorials', 'Tutoriales')], max_length=40)),
                ('language', models.CharField(choices=[('scratch', 'Scratch'), ('python', 'Python'), ('javascript', 'JavaScript')], max_length=40)),
                ('description', models.CharField(max_length=400)),
                ('video', models.CharField(blank=True, max_length=100)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.CharField(blank=True, max_length=100)),
                ('assets', models.CharField(default='{"notebook": ""}', max_length=2000)),
                ('gui', models.CharField(blank=True, max_length=2000)),
                ('referee', models.CharField(blank=True, max_length=2000)),
                ('real', models.CharField(blank=True, max_length=50)),
                ('local', models.CharField(blank=True, max_length=2000)),
                ('compute_load', models.IntegerField(default=100)),
                ('observations', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
