# Generated by Django 4.1.7 on 2025-11-11 14:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_id", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=40, unique=True)),
                ("description", models.CharField(max_length=400)),
                ("tags", models.CharField(default=[], max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("INACTIVE", "INACTIVE"),
                            ("PROTOTYPE", "PROTOTYPE"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("url", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "db_table": '"exercises"',
            },
        ),
        migrations.CreateModel(
            name="Robot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("launch_file_path", models.CharField(max_length=200)),
            ],
            options={
                "db_table": '"robots"',
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("base_config", models.CharField(max_length=200)),
            ],
            options={
                "db_table": '"tools"',
            },
        ),
        migrations.CreateModel(
            name="World",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("launch_file_path", models.CharField(max_length=200)),
                ("tools_config", models.CharField(max_length=200)),
                (
                    "ros_version",
                    models.CharField(
                        choices=[("ROS", "ROS"), ("ROS2", "ROS2")],
                        default="none",
                        max_length=4,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("gazebo", "Gazebo"),
                            ("gz", "Gazebo Harmonic"),
                            ("physical", "Physical"),
                        ],
                        default="none",
                        max_length=50,
                    ),
                ),
                (
                    "start_pose",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.DecimalField(
                                decimal_places=4, default=None, max_digits=10
                            ),
                            size=None,
                        ),
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": '"worlds"',
            },
        ),
        migrations.CreateModel(
            name="Universe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "robot",
                    models.OneToOneField(
                        db_column='"robot_id"',
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.robot",
                    ),
                ),
                (
                    "world",
                    models.OneToOneField(
                        db_column='"world_id"',
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.world",
                    ),
                ),
            ],
            options={
                "db_table": '"universes"',
            },
        ),
        migrations.CreateModel(
            name="ExerciseUniverses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_default", models.BooleanField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.exercise",
                    ),
                ),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.universe",
                    ),
                ),
            ],
            options={
                "db_table": '"exercises_universes"',
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="tools",
            field=models.ManyToManyField(
                db_table='"exercises_tools"', default=None, to="exercises.tool"
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="universes",
            field=models.ManyToManyField(
                default=None,
                through="exercises.ExerciseUniverses",
                to="exercises.universe",
            ),
        ),
    ]
