# Generated by Django 4.1.7 on 2025-11-10 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseUniverses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_default", models.BooleanField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.exercise",
                    ),
                ),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.universe",
                    ),
                ),
            ],
            options={
                "db_table": '"exercises_universes"',
            },
        ),
        migrations.AlterField(
            model_name="exercise",
            name="universes",
            field=models.ManyToManyField(
                default=None,
                through="exercises.ExerciseUniverses",
                to="exercises.universe",
            ),
        ),
    ]
