# Generated by Django 3.2 on 2021-04-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('scratch', 'Scratch'), ('javascript', 'JavaScript')], max_length=40),
        ),
    ]
