# Generated by Django 3.2 on 2021-04-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_alter_exercise_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('scratch', 'Scratch')], max_length=40),
        ),
    ]
