# Generated by Django 3.2 on 2021-04-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_alter_exercise_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='language',
            field=models.CharField(choices=[('scratch', 'Scratch'), ('python', 'Python'), ('javascript', 'JavaScript')], max_length=40),
        ),
    ]
