# Generated by Django 3.2.4 on 2021-06-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_alter_exercise_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='language',
            field=models.CharField(choices=[('scratch', 'Scratch'), ('javascript', 'JavaScript'), ('python', 'Python')], max_length=40),
        ),
    ]
