# Generated by Django 4.0.1 on 2022-02-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_alter_exercise_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='compute_load',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='gui',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='language',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='local',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='real',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='referee',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='state',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='video',
        ),
    ]
