# Generated by Django 4.0.5 on 2022-10-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_alter_exercise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='tags',
            field=models.CharField(default='{"tags": ""}', max_length=2000),
        ),
    ]
