# Generated by Django 4.0.5 on 2022-10-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_exercise_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('PROTOTYPE', 'PROTOTYPE')], default='ACTIVE', max_length=20),
        ),
    ]
