# Generated by Django 2.2.28 on 2023-01-16 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_add_exercise_config'),
        ('exercises', '0015_exercise_status'),
    ]

    operations = [
    ]
