# Generated by Django 4.2.1 on 2023-09-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0017_exercise_visualization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='visualization',
            field=models.CharField(choices=[('none', 'None'), ('console', 'Console'), ('gazebo_gra', 'Gazebo GRA'), ('gazebo_rae', 'Gazebo RAE'), ('physic_gra', 'Physic GRA'), ('physic_rae', 'Physic RAE')], default='INACTIVE', max_length=20),
        ),
    ]
