# Generated by Django 4.2.1 on 2023-10-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0019_alter_exercise_visualization'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='launch_file',
            field=models.TextField(default='/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='model_folders',
            field=models.TextField(default='/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='resource_folders',
            field=models.TextField(default='/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='world',
            field=models.CharField(choices=[('none', 'None'), ('gazebo', 'Gazebo'), ('physical', 'Physical')], default='none', max_length=20),
        ),
    ]
