# Generated by Django 4.2.1 on 2023-10-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0021_remove_exercise_launch_file_exercise_launch_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='resource_folders',
            field=models.TextField(default='{}'),
        ),
    ]
