# Generated by Django 4.2.1 on 2023-10-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0022_alter_exercise_resource_folders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='world',
            field=models.CharField(choices=[('none', 'None'), ('gazebo', 'Gazebo'), ('drones', 'Gazebo Drones'), ('physical', 'Physical')], default='none', max_length=20),
        ),
    ]
