# Generated by Django 4.2.1 on 2023-12-01 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0023_alter_exercise_world'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=uuid.uuid4, max_length=40, unique=True)),
                ('ros_version', models.CharField(choices=[('ROS1', 'ROS1'), ('ROS2', 'ROS2')], default='none', max_length=4)),
                ('world_type', models.CharField(choices=[('none', 'None'), ('gazebo', 'Gazebo'), ('drones', 'Gazebo Drones'), ('physical', 'Physical')], default='none', max_length=20)),
                ('resource_folders', models.TextField(default='')),
                ('model_folders', models.CharField(default='$CUSTOM_ROBOTS_FOLDER/', max_length=100)),
                ('launch_file', models.TextField(default='{}')),
            ],
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='world',
            new_name='world_type',
        ),
        migrations.AddField(
            model_name='exercise',
            name='worlds',
            field=models.ManyToManyField(default=None, to='exercises.world'),
        ),
    ]
