# Generated by Django 4.2 on 2023-11-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0023_alter_exercise_world'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='model_folders',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='resource_folders',
        ),
    ]
