# Generated by Django 4.2.1 on 2023-12-01 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0024_world_rename_world_exercise_world_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='launch_files',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='model_folders',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='resource_folders',
        ),
    ]
