# Generated by Django 4.2 on 2023-12-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0024_remove_exercise_assets_remove_exercise_model_folders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('launch_file_path', models.CharField(max_length=200)),
                ('ros_version', models.CharField(choices=[('ROS1', 'ROS1'), ('ROS2', 'ROS2')], default='none', max_length=4)),
                ('visualization', models.CharField(choices=[('none', 'None'), ('console', 'Console'), ('gazebo_gra', 'Gazebo GRA'), ('gazebo_rae', 'Gazebo RAE'), ('physic_gra', 'Physic GRA'), ('physic_rae', 'Physic RAE')], default='none', max_length=50)),
                ('world', models.CharField(choices=[('none', 'None'), ('gazebo', 'Gazebo'), ('drones', 'Gazebo Drones'), ('physical', 'Physical')], default='none', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='launch_files',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='visualization',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='world',
        ),
        migrations.AddField(
            model_name='exercise',
            name='worlds',
            field=models.ManyToManyField(default=None, to='exercises.world'),
        ),
    ]
