# Generated by Django 4.2.1 on 2023-12-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0025_remove_exercise_launch_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='auxiliar_components',
            field=models.TextField(default='{}'),
        ),
    ]
