# Generated by Django 4.2 on 2023-12-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0025_world_remove_exercise_configuration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='template',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
