# Generated by Django 4.1.7 on 2024-07-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0026_exercise_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='visualization',
            field=models.CharField(choices=[('none', 'None'), ('console', 'Console'), ('gazebo_gra', 'Gazebo GRA'), ('gazebo_rae', 'Gazebo RAE'), ('gzsim_gra', 'Gz Sim GRA'), ('gzsim_rae', 'Gz Sim RAE'), ('physic_gra', 'Physic GRA'), ('physic_rae', 'Physic RAE')], default='none', max_length=50),
        ),
    ]
