# Generated by Django 4.1.7 on 2024-08-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0027_alter_world_visualization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='world',
            field=models.CharField(choices=[('none', 'None'), ('gazebo', 'Gazebo'), ('drones', 'Gazebo Drones'), ('gzsimdrones', 'Gz Sim Drones'), ('physical', 'Physical')], default='none', max_length=50),
        ),
    ]
