FROM jderobot/robotics-applications:dependencies-humble

WORKDIR /

# RoboticsInfrasctructure Repository
ARG ROBOTICS_INFRASTRUCTURE=$ROBOTICS_INFRASTRUCTURE
ARG INFRA_OWNER=JdeRobot
RUN mkdir -p /opt/jderobot && \
    git clone --depth 1 https://github.com/${INFRA_OWNER}/RoboticsInfrastructure.git -b $ROBOTICS_INFRASTRUCTURE /opt/jderobot

# create workspace and add Robot packages
RUN mkdir -p /home/ws/src
RUN mv /opt/jderobot/CustomRobots /opt/jderobot/jderobot_drones /opt/jderobot/jderobot_drones_cpp /opt/jderobot/Industrial /opt/jderobot/common_interfaces_cpp /home/ws/src/
RUN mv /opt/jderobot/resources /resources

ARG IMAGE_TAG
ENV IMAGE_TAG=${IMAGE_TAG}

# Clone the RoboticsApplicationManager repository into the src folder inside RoboticsAcademy
RUN python3 -m pip install --no-cache-dir robotics_application_manager

# copy scripts
RUN mv -t / /opt/jderobot/scripts/.env  /opt/jderobot/scripts/entrypoint.sh /opt/jderobot/scripts/ram_entrypoint.py /opt/jderobot/scripts/start_vnc.sh  /opt/jderobot/scripts/start_vnc_gpu.sh /opt/jderobot/scripts/kill_all.sh /opt/jderobot/scripts/test/check_device.py /opt/jderobot/scripts/set_dri_name.sh /opt/jderobot/scripts/check_ram_version.sh

# Move Window Manager config
RUN mv -f /opt/jderobot/scripts/rc.xml /etc/xdg/openbox/LXDE/rc.xml

# give execution permissions
WORKDIR /
RUN chmod +x /start_vnc.sh /kill_all.sh /entrypoint.sh /start_vnc_gpu.sh /set_dri_name.sh

# RoboticsAcademy
ARG ROBOTICS_ACADEMY=$ROBOTICS_ACADEMY
ARG ACADEMY_OWNER=JdeRobot
RUN git clone --depth 1 https://github.com/${ACADEMY_OWNER}/RoboticsAcademy.git -b $ROBOTICS_ACADEMY /RoboticsAcademy/

# Compiling and sourcing the workspace
WORKDIR /home/ws
# RUN /bin/bash -c "source /home/drones_ws/install/setup.bash"
# RUN /bin/bash -c "source /home/dev_ws/install/local_setup.bash"
RUN /bin/bash -c "source /opt/ros/jazzy/setup.bash; colcon build --symlink-install"

# Compress commons
WORKDIR /RoboticsAcademy/
RUN cd /RoboticsAcademy/common && cd console_interfaces && zip -r ../common.zip console_interfaces/ && cd .. && cd gui_interfaces && zip -r -u ../common.zip gui_interfaces/ && cd .. && cd hal_interfaces && zip -r -u ../common.zip hal_interfaces/ && cd ../.. && mv common/common.zip react_frontend/src/common.zip

# build react_fronted
RUN cd /RoboticsAcademy/react_frontend/ && yarn install && yarn run build

# Django server
EXPOSE 7164

# Manager websocket
EXPOSE 7163

# Tools ports
EXPOSE 6080-6090

#PostgreSQL Database
EXPOSE 5432

WORKDIR /

# Setting environment in both interactive or non-interactive shells
ENV BASH_ENV=/.env
ENTRYPOINT ["./entrypoint.sh"]