FROM ros:lyrical-ros-core-resolute

# Make all NVIDIA GPUS visible
ARG NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all
ENV VIRTUALGL_VERSION=3.1.5
ENV TURBOVNC_VERSION=3.3.1

# Install common tools
RUN apt-get update && apt-get install -y \
  software-properties-common \
  bash-completion \
  apt-utils \
  curl wget cmake \
  nano vim git\
  gnupg \
  lsb-release ca-certificates\
  sudo xterm\
  net-tools \
  pciutils \
  nlohmann-json3-dev \
  python3.14-venv \
  python3-pip \
  openssh-server \
  && rm -rf /var/lib/apt/lists/*

# Setup python env
RUN python3.14 -m venv /.venv
ENV PATH="/.venv/bin:$PATH"

# Configure Gazebo Jetty
RUN apt-get update && apt-get install -y ros-${ROS_DISTRO}-ros-gz

# Configure VNC
RUN apt-get update && apt-get install -y dbus-x11 lxde-common
RUN git clone --recursive -b v1.7.0 https://github.com/novnc/noVNC.git
RUN cd /noVNC/utils && git clone --depth=1 --single-branch -b v0.13.0 https://github.com/novnc/websockify.git

# VirtualGL
RUN wget -q -O- https://packagecloud.io/dcommander/virtualgl/gpgkey | gpg --dearmor >/etc/apt/trusted.gpg.d/VirtualGL.gpg \
  && echo "deb [signed-by=/etc/apt/trusted.gpg.d/VirtualGL.gpg] https://packagecloud.io/dcommander/virtualgl/any/ any main" > /etc/apt/sources.list.d/virtualgl.list \
  && apt-get update && apt-get install -y virtualgl

# TurboVNC
RUN wget -q -O- https://packagecloud.io/dcommander/turbovnc/gpgkey | gpg --dearmor >/etc/apt/trusted.gpg.d/TurboVNC.gpg \
  && echo "deb [signed-by=/etc/apt/trusted.gpg.d/TurboVNC.gpg] https://packagecloud.io/dcommander/turbovnc/any/ any main" > /etc/apt/sources.list.d/turbovnc.list \
  && apt-get update && apt-get install -y turbovnc

# Install postgreSQL-18
RUN wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/pgdg.gpg \
  && echo "deb [signed-by=/usr/share/keyrings/pgdg.gpg] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
  && apt-get update && apt-get install -y --no-install-recommends postgresql-18 \
  && rm -rf /var/lib/apt/lists/*


# Install Python 3 pip build dependencies first
RUN python3.14 -m pip install --no-cache-dir --upgrade pip wheel setuptools

# pip install dependencies
RUN python3.14 -m pip install --no-cache-dir \
  pylint transitions pydantic websocket-client\
  argparse coverage cerberus empy jinja2 kconfiglib \
  matplotlib numpy nunavut packaging pkgconfig pyros-genmsg \
  pyulog pyyaml requests serial six toml psutil \
  onnxruntime-gpu Pillow opencv-python watchdog utm psycopg2 jedi pyapriltags black flake8 \
  cmakelint chardet lark colcon-common-extensions \
  cpplint \
  transforms3d \
  colcon-lcov-result \
  PySimpleGUI-4-foss \
  colcon-cmake


# websocket server dependency
RUN python3.14 -m pip install --no-cache-dir websocket_server posix-ipc django djangorestframework \
  django-webpack-loader django-cors-headers asyncio


# Configure Ros dependencies
RUN apt-get update && \
  apt-get install -y \
  libbenchmark-dev \
  libeigen3-dev \
  libgeographiclib-dev \
  libncurses-dev \
  libyaml-cpp-dev \
  pybind11-dev \
  python3-jinja2 \
  python3-pydantic \
  python3-pymap3d \
  python3-pytest \
  python3-rosdep \
  python3-colcon-common-extensions \
  python3-colcon-mixin \
  python-is-python3 \
  python3-flake8 \
  python3-flake8-builtins  \
  python3-flake8-comprehensions \
  python3-flake8-docstrings \
  python3-flake8-import-order \
  python3-flake8-quotes \
  cppcheck \
  ros-dev-tools \
  ros-${ROS_DISTRO}-action-msgs \
  ros-${ROS_DISTRO}-ament-cmake \
  ros-${ROS_DISTRO}-ament-cmake-gtest \
  ros-${ROS_DISTRO}-ament-cmake-lint-cmake \
  ros-${ROS_DISTRO}-ament-cmake-pytest \
  ros-${ROS_DISTRO}-ament-cmake-python \
  ros-${ROS_DISTRO}-ament-cmake-xmllint \
  ros-${ROS_DISTRO}-ament-copyright \
  ros-${ROS_DISTRO}-ament-flake8 \
  ros-${ROS_DISTRO}-ament-index-cpp \
  ros-${ROS_DISTRO}-ament-lint-auto \
  ros-${ROS_DISTRO}-ament-lint-common \
  ros-${ROS_DISTRO}-ament-pep257 \
  ros-${ROS_DISTRO}-backward-ros \
  ros-${ROS_DISTRO}-builtin-interfaces \
  ros-${ROS_DISTRO}-cv-bridge \
  ros-${ROS_DISTRO}-geographic-msgs \
  ros-${ROS_DISTRO}-geometry-msgs \
  ros-${ROS_DISTRO}-image-transport \
  # ros-${ROS_DISTRO}-mocap4r2-msgs \
  ros-${ROS_DISTRO}-nav-msgs \
  ros-${ROS_DISTRO}-pluginlib \
  ros-${ROS_DISTRO}-rclcpp \
  ros-${ROS_DISTRO}-rclcpp-action \
  ros-${ROS_DISTRO}-rclcpp-components \
  ros-${ROS_DISTRO}-rclcpp-lifecycle \
  ros-${ROS_DISTRO}-rclpy \
  ros-${ROS_DISTRO}-robot-state-publisher \
  ros-${ROS_DISTRO}-rosidl-default-generators \
  ros-${ROS_DISTRO}-rosidl-default-runtime \
  ros-${ROS_DISTRO}-rviz2 \
  ros-${ROS_DISTRO}-sdformat-urdf \
  ros-${ROS_DISTRO}-sensor-msgs \
  ros-${ROS_DISTRO}-std-msgs \
  ros-${ROS_DISTRO}-std-srvs \
  ros-${ROS_DISTRO}-tf2 \
  ros-${ROS_DISTRO}-tf2-geometry-msgs \
  ros-${ROS_DISTRO}-tf2-msgs \
  ros-${ROS_DISTRO}-tf2-ros \
  ros-${ROS_DISTRO}-trajectory-msgs \
  ros-${ROS_DISTRO}-visualization-msgs \
  ros-${ROS_DISTRO}-moveit \
  ros-${ROS_DISTRO}-ros2-control \
  ros-${ROS_DISTRO}-gz-ros2-control \
  ros-${ROS_DISTRO}-ros2-controllers \
  # ros-${ROS_DISTRO}-gripper-controllers \
  ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
  ros-${ROS_DISTRO}-ur \
  ros-${ROS_DISTRO}-ros-testing \
  ros-${ROS_DISTRO}-pcl-ros \
  ros-${ROS_DISTRO}-tf-transformations \
  ros-${ROS_DISTRO}-pcl-conversions \
  ros-${ROS_DISTRO}-pcl-msgs \
  ros-${ROS_DISTRO}-ompl\
  ros-${ROS_DISTRO}-unique-identifier-msgs \
  ros-${ROS_DISTRO}-service-msgs \
  # ros-${ROS_DISTRO}-rosidl-adapter \
  # ros-${ROS_DISTRO}-rosidl-buffer \
  # ros-${ROS_DISTRO}-rosidl-buffer-backend \
  # ros-${ROS_DISTRO}-rosidl-buffer-backend-registry \
  # ros-${ROS_DISTRO}-rosidl-buffer-backend-registry-dbgsym \
  # ros-${ROS_DISTRO}-rosidl-buffer-dbgsym \
  # ros-${ROS_DISTRO}-rosidl-buffer-py \
  # ros-${ROS_DISTRO}-rosidl-buffer-py-dbgsym \
  # ros-${ROS_DISTRO}-rosidl-cli \
  # ros-${ROS_DISTRO}-rosidl-cmake \
  # ros-${ROS_DISTRO}-rosidl-core-generators \
  # ros-${ROS_DISTRO}-rosidl-core-runtime \
  # ros-${ROS_DISTRO}-rosidl-default-generators  \
  # ros-${ROS_DISTRO}-rosidl-default-runtime \
  # ros-${ROS_DISTRO}-rosidl-dynamic-typesupport \
  # ros-${ROS_DISTRO}-rosidl-dynamic-typesupport-dbgsym \
  ros-${ROS_DISTRO}-rosidl-dynamic-typesupport-fastrtps \
  # ros-${ROS_DISTRO}-rosidl-dynamic-typesupport-fastrtps-dbgsym \
  # ros-${ROS_DISTRO}-rosidl-generator-c \
  # ros-${ROS_DISTRO}-rosidl-generator-cpp \
  # ros-${ROS_DISTRO}-rosidl-generator-dds-idl \
  # ros-${ROS_DISTRO}-rosidl-generator-py \
  # ros-${ROS_DISTRO}-rosidl-generator-rs \
  # ros-${ROS_DISTRO}-rosidl-generator-type-description \
  # ros-${ROS_DISTRO}-rosidl-parser \
  # ros-${ROS_DISTRO}-rosidl-pycommon \
  # ros-${ROS_DISTRO}-rosidl-runtime-c \
  # ros-${ROS_DISTRO}-rosidl-runtime-c-dbgsym \
  # ros-${ROS_DISTRO}-rosidl-runtime-cpp \
  # ros-${ROS_DISTRO}-rosidl-runtime-py \
  # ros-${ROS_DISTRO}-rosidl-typesupport-c \
  # ros-${ROS_DISTRO}-rosidl-typesupport-c-dbgsym \
  # ros-${ROS_DISTRO}-rosidl-typesupport-cpp \
  # ros-${ROS_DISTRO}-rosidl-typesupport-cpp-dbgsym \
  ros-${ROS_DISTRO}-rosidl-typesupport-fastrtps-c \
  ros-${ROS_DISTRO}-rosidl-typesupport-fastrtps-cpp \
  # ros-${ROS_DISTRO}-rosidl-typesupport-fastrtps-c-dbgsym \
  # ros-${ROS_DISTRO}-rosidl-typesupport-fastrtps-cpp-dbgsym \
  # ros-${ROS_DISTRO}-rosidl-typesupport-interface \
  # ros-${ROS_DISTRO}-rosidl-typesupport-introspection-c \
  # ros-${ROS_DISTRO}-rosidl-typesupport-introspection-c-dbgsym \
  # ros-${ROS_DISTRO}-rosidl-typesupport-introspection-cpp \
  # ros-${ROS_DISTRO}-rosidl-typesupport-introspection-cpp-dbgsym \
  # ros-${ROS_DISTRO}-rosidlcpp \
  # ros-${ROS_DISTRO}-rosidlcpp-generator-c \
  # ros-${ROS_DISTRO}-rosidlcpp-generator-c-dbgsym \
  # ros-${ROS_DISTRO}-rosidlcpp-generator-core \
  # ros-${ROS_DISTRO}-rosidlcpp-generator-core-dbgsym \
  # ros-${ROS_DISTRO}-rosidlcpp-generator-cpp \
  # ros-${ROS_DISTRO}-rosidlcpp-generator-cpp-dbgsym \
  # ros-${ROS_DISTRO}-rosidlcpp-generator-py \
  # ros-${ROS_DISTRO}-rosidlcpp-generator-py-dbgsym \
  # ros-${ROS_DISTRO}-rosidlcpp-generator-type-description \
  # ros-${ROS_DISTRO}-rosidlcpp-generator-type-description-dbgsym \
  # ros-${ROS_DISTRO}-rosidlcpp-parser \
  # ros-${ROS_DISTRO}-rosidlcpp-parser-dbgsym \
  # ros-${ROS_DISTRO}-rosidlcpp-typesupport-c \
  # ros-${ROS_DISTRO}-rosidlcpp-typesupport-c-dbgsym \
  # ros-${ROS_DISTRO}-rosidlcpp-typesupport-cpp \
  # ros-${ROS_DISTRO}-rosidlcpp-typesupport-cpp-dbgsym \
  ros-${ROS_DISTRO}-rosidlcpp-typesupport-fastrtps-c \
  # ros-${ROS_DISTRO}-rosidlcpp-typesupport-fastrtps-c-dbgsym \
  ros-${ROS_DISTRO}-rosidlcpp-typesupport-fastrtps-cpp \
  # ros-${ROS_DISTRO}-rosidlcpp-typesupport-fastrtps-cpp-dbgsym \
  # ros-${ROS_DISTRO}-rosidlcpp-typesupport-introspection-c \
  # ros-${ROS_DISTRO}-rosidlcpp-typesupport-introspection-c-dbgsym \
  # ros-${ROS_DISTRO}-rosidlcpp-typesupport-introspection-cpp \
  # ros-${ROS_DISTRO}-rosidlcpp-typesupport-introspection-cpp-dbgsym \
  libpoco-dev \
  libpcl-dev \
  libompl-dev \
  && rm -rf /var/lib/apt/lists/*


# RUN python3.14 -m pip install --no-cache-dir ompl

## Aerostack2
### Remove log folder
RUN rm -rf log 
RUN mkdir -p /home/drones_ws/src/

WORKDIR /home/drones_ws/src/
RUN git clone --depth=1 https://github.com/aerostack2/aerostack2.git -b robotics-academy-fix
RUN touch aerostack2/as2_hardware_drivers/COLCON_IGNORE
RUN touch aerostack2/as2_behavior_tree/COLCON_IGNORE
RUN touch aerostack2/as2_map_server/COLCON_IGNORE
RUN touch aerostack2/as2_behaviors/as2_behaviors_path_planning/COLCON_IGNORE
RUN touch aerostack2/as2_utilities/as2_geozones/COLCON_IGNORE
RUN touch aerostack2/as2_user_interfaces/as2_visualization/as2_rviz_plugins/COLCON_IGNORE

WORKDIR /home/drones_ws/

# On arm64 (e.g. Apple Silicon), disable parallel colcon builds and LTO
# to avoid GNU make jobserver failures under amd64 emulation.

# ARG TARGETARCH
# RUN . /opt/ros/$ROS_DISTRO/setup.sh && \
#   if [ "$TARGETARCH" = "arm64" ]; then \
#   colcon build \
#   --symlink-install \
#   --executor sequential \
#   --cmake-args \
#   -DCMAKE_BUILD_TYPE=Release \
#   -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF ; \
#   else \
#   colcon build \
#   --symlink-install \
#   --cmake-args \
#   -DCMAKE_BUILD_TYPE=Release ; \
#   fi


# Create workspace and add drone packages
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc
RUN echo 'export AEROSTACK2_PATH=/home/drones_ws/src/aerostack2' >> ~/.bashrc
RUN echo 'source $AEROSTACK2_PATH/as2_cli/setup_env.bash' >> ~/.bashrc
RUN echo "source /home/drones_ws/install/setup.bash" >> ~/.bashrc

# # Configure SSH
# RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
# RUN sed -i 's/#Port 22/Port 8081/' /etc/ssh/sshd_config
# RUN ssh-keygen -y -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
# RUN mkdir -p /run/sshd && chmod 755 /run/sshd
# RUN echo 'hare' | passwd --stdin root 


# Configure proxy
# COPY proxy/traefik /usr/bin/traefik
# RUN mkdir /etc/traefik
# WORKDIR /etc/traefik
# COPY proxy/traefik.yaml /etc/traefik
# COPY proxy/routes.yaml /etc/traefik


