FROM node:24 AS ra-base

RUN apt-get update && apt-get install -y git zip

# RoboticsAcademy
ARG ROBOTICS_ACADEMY=$ROBOTICS_ACADEMY
ARG ACADEMY_OWNER=JdeRobot
RUN mkdir -p /tmp/dev
COPY ./ /tmp/app
WORKDIR /tmp/app
RUN cd common && cd console_interfaces && zip -r ../common.zip console_interfaces/ && cd .. && cd gui_interfaces && zip -r -u ../common.zip gui_interfaces/ && cd .. && cd hal_interfaces && zip -r -u ../common.zip hal_interfaces/ && cd ../.. && mv common/common.zip react_frontend/src/common.zip
WORKDIR /tmp/app/react_frontend
RUN yarn install && yarn run build


FROM jderobot/robotics-applications:dependencies-lyrical

WORKDIR /

# RoboticsInfrasctructure Repository
ARG ROBOTICS_INFRASTRUCTURE=$ROBOTICS_INFRASTRUCTURE
ARG INFRA_OWNER=JdeRobot
# Launchers/, Scenes/, Universes/ are intentionally retained in /opt/jderobot (hardcoded in all launch files).
# Only .git history is stripped to recover extra space.
COPY ./RoboticsInfrastructure /opt/jderobot
RUN mkdir -p /opt/jderobot /home/ws/src && \
    mv /opt/jderobot/CustomRobots /opt/jderobot/jderobot_drones /opt/jderobot/jderobot_drones_cpp /opt/jderobot/Industrial /opt/jderobot/common_interfaces_cpp /home/ws/src/ && \
    mv /opt/jderobot/resources /resources && \
    mv -t / /opt/jderobot/scripts/.env /opt/jderobot/scripts/entrypoint.sh /opt/jderobot/scripts/ram_entrypoint.py /opt/jderobot/scripts/test/check_device.py /opt/jderobot/scripts/set_dri_name.sh /opt/jderobot/scripts/check_ram_version.sh && \
    mv -f /opt/jderobot/scripts/rc.xml /etc/xdg/openbox/LXDE/rc.xml && \
    chmod +x /entrypoint.sh /set_dri_name.sh && \
    rm -rf /opt/jderobot/.git \
    /opt/jderobot/.github \
    /opt/jderobot/database \
    /opt/jderobot/deprecated_assets \
    /opt/jderobot/Docs \
    /opt/jderobot/test \
    /opt/jderobot/Universes \
    /opt/jderobot/utils \
    && rm -f /opt/jderobot/Scenes/*.glb

RUN rm /etc/xdg/autostart/lxpolkit.desktop
RUN rm /usr/bin/lxpolkit

# Install and config traefik
RUN wget https://github.com/traefik/traefik/releases/download/v3.7.14/traefik_v3.7.14_linux_amd64.tar.gz && tar -xzf traefik_*.tar.gz && mv traefik /usr/bin/
RUN mkdir /etc/traefik
COPY ./RoboticsInfrastructure/scripts/proxy /etc/traefik

# COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

ARG IMAGE_TAG
ENV IMAGE_TAG=${IMAGE_TAG}

# Clone the RoboticsApplicationManager repository into the src folder inside RoboticsAcademy
COPY ./src /RoboticsApplicationManager

# Build react_fronted and create commons
COPY ./ /RoboticsAcademy
RUN rm -rf /RoboticsAcademy/.git \
    /RoboticsAcademy/compose_cfg \
    /RoboticsAcademy/docs \
    /RoboticsAcademy/scripts \
    /RoboticsAcademy/tests \
    /RoboticsAcademy/react_frontend \
    /RoboticsAcademy/common

COPY --from=ra-base /tmp/app/react_frontend/static /RoboticsAcademy/react_frontend/static
COPY --from=ra-base /tmp/app/react_frontend/templates /RoboticsAcademy/react_frontend/templates
COPY --from=ra-base /tmp/app/react_frontend/__init__.py /RoboticsAcademy/react_frontend/__init__.py
COPY --from=ra-base /tmp/app/react_frontend/apps.py /RoboticsAcademy/react_frontend/apps.py
COPY --from=ra-base /tmp/app/react_frontend/urls.py /RoboticsAcademy/react_frontend/urls.py
COPY --from=ra-base /tmp/app/react_frontend/views.py /RoboticsAcademy/react_frontend/views.py
COPY --from=ra-base /tmp/app/react_frontend/webpack-stats.json /RoboticsAcademy/react_frontend/webpack-stats.json

# Compiling and sourcing the workspace
WORKDIR /home/ws
RUN /bin/bash -c "source /opt/ros/lyrical/setup.bash; colcon build --symlink-install --continue-on-error; exit 0"
RUN mv /usr/share/xsessions/LXDE.desktop /usr/share/xsessions/startlxde.desktop
RUN python3.14 -m pip install --no-cache-dir websockets

# Django server
EXPOSE 7164

# Manager websocket
EXPOSE 7163

# Tools ports
EXPOSE 6080-6090

#PostgreSQL Database
EXPOSE 5432

WORKDIR /

# Setting environment in both interactive or non-interactive shells
ENV BASH_ENV=/.env
ENTRYPOINT ["./entrypoint.sh"]