FROM ra-base

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=humble

# Add Gazebo repo (THIS IS WHAT YOU MISSED)
RUN apt-get update && apt-get install -y software-properties-common && \
    add-apt-repository ppa:openrobotics/gazebo11-gz-cli

# Install Gazebo + ROS integration
RUN apt-get update && apt-get install -y --no-install-recommends \
    gazebo11 \
    ros-${ROS_DISTRO}-gazebo-ros-pkgs \
    && rm -rf /var/lib/apt/lists/*

# Minimal GUI
RUN apt-get update && apt-get install -y --no-install-recommends \
    x11-apps \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p ~/.gazebo && touch ~/.gazebo/gui.ini
