FROM jderobot/robotics-applications:dependencies-humble

WORKDIR /

# RoboticsInfrasctructure Repository (from anishk85 fork)
ARG ROBOTICS_INFRASTRUCTURE=${ROBOTICS_INFRASTRUCTURE:-feature/pick-place-harmonic-launchers}
RUN mkdir -p /opt/jderobot && \
    git clone --depth 1 https://github.com/anishk85/RoboticsInfrastructure.git -b $ROBOTICS_INFRASTRUCTURE /opt/jderobot

# create workspace and add Robot packages
RUN mkdir -p /home/ws/src
RUN mv /opt/jderobot/CustomRobots /opt/jderobot/jderobot_drones /home/ws/src/
RUN mv /opt/jderobot/resources /resources

ARG IMAGE_TAG
ENV IMAGE_TAG=${IMAGE_TAG}

# Clone the RoboticsApplicationManager repository into the src folder inside RoboticsAcademy
ARG RAM=$RAM
RUN git clone https://github.com/JdeRobot/RoboticsApplicationManager.git -b $RAM /RoboticsApplicationManager

# copy scripts
RUN mv -t / /opt/jderobot/scripts/.env  /opt/jderobot/scripts/entrypoint.sh /opt/jderobot/scripts/start_vnc.sh  /opt/jderobot/scripts/start_vnc_gpu.sh /opt/jderobot/scripts/kill_all.sh /opt/jderobot/scripts/test/check_device.py /opt/jderobot/scripts/set_dri_name.sh

# Move Window Manager config
RUN mv -f /opt/jderobot/scripts/rc.xml /etc/xdg/openbox/LXDE/rc.xml

# give execution permissions
WORKDIR /
RUN chmod +x /start_vnc.sh /kill_all.sh /entrypoint.sh /start_vnc_gpu.sh /set_dri_name.sh

# RoboticsAcademy (from anishk85 fork)
ARG ROBOTICS_ACADEMY=${ROBOTICS_ACADEMY:-feature/pick-place-harmonic}
RUN git clone --depth 1 https://github.com/anishk85/RoboticsAcademy.git -b $ROBOTICS_ACADEMY /RoboticsAcademy/

# Compiling and sourcing the workspace
WORKDIR /home/ws
RUN /bin/bash -c "source /home/drones_ws/install/setup.bash"
RUN /bin/bash -c "source /home/dev_ws/install/local_setup.bash"
RUN /bin/bash -c "source /opt/ros/humble/setup.bash; colcon build --symlink-install"

# Clone and build gz_ros2_control for Gazebo Harmonic (gz-sim8)
# This is required for Pick Place Harmonic exercise controller loading
WORKDIR /home/dev_ws/src/IndustrialRobots/pick_place_harmonic_exercise
RUN git clone --depth 1 https://github.com/ros-controls/gz_ros2_control.git -b humble
WORKDIR /home/dev_ws/src/IndustrialRobots/pick_place_harmonic_exercise/gz_ros2_control
RUN /bin/bash -c "source /opt/ros/humble/setup.bash && \
    export GZ_VERSION=harmonic && \
    colcon build --packages-select gz_ros2_control --allow-overriding gz_ros2_control"

# Compress commons
WORKDIR /RoboticsAcademy/
RUN cd /RoboticsAcademy/common && cd console_interfaces && zip -r ../common.zip console_interfaces/ && cd .. && cd gui_interfaces && zip -r -u ../common.zip gui_interfaces/ && cd .. && cd hal_interfaces && zip -r -u ../common.zip hal_interfaces/ && cd ../.. && mv common/common.zip react_frontend/src/common.zip

# build react_fronted
RUN cd /RoboticsAcademy/react_frontend/ && yarn install && yarn run build

# Django server
EXPOSE 7164

# Manager websocket
EXPOSE 7163

# Tools ports
EXPOSE 6080-6090

#PostgreSQL Database
EXPOSE 5432

WORKDIR /

# Setting environment in both interactive or non-interactive shells
ENV BASH_ENV=/.env
ENTRYPOINT ["./entrypoint.sh"]