FROM nvidia/opengl:1.2-glvnd-runtime-ubuntu22.04
# Optional components
ARG INSTALL_AEROSTACK=false
ARG INSTALL_GZ_CONTROL=false
# Make all NVIDIA GPUS visible
ARG NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all
ENV VIRTUALGL_VERSION=3.1.4
ENV TURBOVNC_VERSION=3.0.3

# Setup NON INTERACTIVE ENVIRONMENT
ENV DEBIAN_FRONTEND=noninteractive

# Install locales to prevent errors
RUN apt-get clean && \
  apt-get update && \
  apt-get install --no-install-recommends -y locales && \
  rm -rf /var/lib/apt/lists/* && \
  locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

ENV ROS_DISTRO=humble
ENV AMENT_PREFIX_PATH=/opt/ros/${ROS_DISTRO}
ENV COLCON_PREFIX_PATH=/opt/ros/${ROS_DISTRO}
ENV LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/gazebo-11/plugins:/opt/ros/${ROS_DISTRO}/opt/rviz_ogre_vendor/lib:/opt/ros/${ROS_DISTRO}/lib/x86_64-linux-gnu:/opt/ros/${ROS_DISTRO}/lib:/usr/share/gazebo/../../lib/x86_64-linux-gnu/gazebo-11/plugins:
ENV PATH=/opt/ros/${ROS_DISTRO}/bin:$PATH
ENV PYTHONPATH=/opt/ros/${ROS_DISTRO}/lib/python3.10/site-packages
ENV ROS_PYTHON_VERSION=3
ENV ROS_VERSION=2
# Install common tools
RUN apt-get update && apt-get install -y \
  software-properties-common \
  bash-completion \
  apt-utils \
  build-essential \
  git curl wget cmake \
  nano vim \
  gnupg \
  lsb-release \
  sudo \
  net-tools \
  pciutils \
  && rm -rf /var/lib/apt/lists/*

# Install ROS2 and ROS packages
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg \
  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null \
  && apt-get update && apt-get install -y \
  ros-${ROS_DISTRO}-ros-base \
  ros-${ROS_DISTRO}-xacro \
  ros-${ROS_DISTRO}-joint-state-publisher \
  ros-${ROS_DISTRO}-rviz2 \
  python3-colcon-common-extensions \
  python3-pip python3-rosdep python3-vcstool \
  python3-argcomplete \
  && rosdep init \
  && rm -rf /var/lib/apt/lists/*

# Install Gazebo 11
RUN add-apt-repository ppa:openrobotics/gazebo11-gz-cli
RUN apt-get update && apt-get install -y --no-install-recommends \
  gazebo11 \
  ros-humble-gazebo-ros-pkgs \
  gstreamer1.0-plugins-bad \
  gstreamer1.0-plugins-good \
  gstreamer1.0-plugins-ugly \
  gstreamer1.0-libav \
  libimage-exiftool-perl \
  && apt-get -y autoremove \
  && apt-get clean autoclean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN mkdir ~/.gazebo && touch ~/.gazebo/gui.ini

# Optional: gz_ros2_control (extension point)
RUN if [ "$INSTALL_GZ_CONTROL" = "true" ]; then \
  echo "gz_ros2_control support can be added here"; \
fi

# Optional: Aerostack2 (extension point)
RUN if [ "$INSTALL_AEROSTACK" = "true" ]; then \
  echo "Aerostack2 support can be added here"; \
fi

# Install VNC
# Xorg segfault error mitigation
RUN apt-get update && apt-get install -y --no-install-recommends \
  dbus-x11 \
  libdbus-c++-1-0v5 \
  xvfb xauth xfonts-base xkb-data x11-xkb-utils \
  x11vnc \
  xterm \
  xserver-xorg-video-dummy \
  x11-apps \
  && apt-get -y autoremove \
  && apt-get clean autoclean \
  && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

RUN curl -L -o xorg.conf https://xpra.org/xorg.conf || echo "Download failed" \
  && rm -rf /tmp/*

# Install noVNC and websockify
RUN git clone -b v1.4.0 https://github.com/novnc/noVNC.git
RUN cd /noVNC/utils && git clone -b v0.11.0 https://github.com/novnc/websockify.git

# VirtualGL and TurboVNC
COPY ./gpu/virtualgl_${VIRTUALGL_VERSION}_amd64.deb ./gpu/virtualgl32_${VIRTUALGL_VERSION}_amd64.deb ./gpu/turbovnc_${TURBOVNC_VERSION}_amd64.deb /

RUN dpkg --add-architecture i386 && apt-get update && apt-get install -y \
  libxtst6:i386 \
  libxv1:i386 \
  libglu1-mesa:i386 \
  libegl1-mesa:i386 \
  libegl1-mesa:amd64

RUN apt-get update && dpkg -i /virtualgl_${VIRTUALGL_VERSION}_amd64.deb /virtualgl32_${VIRTUALGL_VERSION}_amd64.deb \
  && rm /virtualgl_${VIRTUALGL_VERSION}_amd64.deb /virtualgl32_${VIRTUALGL_VERSION}_amd64.deb \
  && chmod u+s /usr/lib/libvglfaker.so \
  && chmod u+s /usr/lib/libdlfaker.so \
  && chmod u+s /usr/lib32/libvglfaker.so \
  && chmod u+s /usr/lib32/libdlfaker.so \
  && chmod u+s /usr/lib/i386-linux-gnu/libvglfaker.so \
  && chmod u+s /usr/lib/i386-linux-gnu/libdlfaker.so \
  && apt-get update && apt-get install -y --no-install-recommends \
  /turbovnc_${TURBOVNC_VERSION}_amd64.deb \
  && rm turbovnc_${TURBOVNC_VERSION}_amd64.deb \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
  apt-get install -y lxde-common && \
  rm -rf /var/lib/apt/lists/*

ENV PATH="$PATH:/opt/VirtualGL/bin:/opt/TurboVNC/bin"

# Install postgreSQL-18
RUN apt-get update && apt-get install -y --no-install-recommends \
  wget gnupg lsb-release ca-certificates \
  && wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/pgdg.gpg \
  && echo "deb [signed-by=/usr/share/keyrings/pgdg.gpg] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
  && apt-get update && apt-get install -y --no-install-recommends postgresql-18 \
  && rm -rf /var/lib/apt/lists/*

# Node
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash - \
  && apt-get install -y nodejs \
  && npm install -g yarn

# Install Python 3 pip build dependencies first
RUN python3.10 -m pip install --upgrade pip==23.3.1 wheel==0.41.3 setuptools==69.0.2 selenium

# pip install dependencies
RUN python3.10 -m pip install \
  pylint==3.3.1 transitions==0.9.0 pydantic==2.4.2 websocket-client==1.5.2 \
  argparse==1.4.0 coverage==6.2 cerberus==1.3.4 empy==3.3.4 jinja2==3.0.3 kconfiglib==14.1.0 \
  matplotlib==3.0.* numpy==1.24.3 nunavut==1.1.0 packaging==21.3 pkgconfig==1.5.5 pyros-genmsg==0.5.8 \
  pyulog==1.0.1 pyyaml==5.4.1 requests==2.31.0 serial==0.0.97 six==1.16.0 toml==0.10.2 psutil==5.9.0 \
  onnxruntime-gpu==1.22.0 Pillow==9.0.1 opencv-python==4.5.5.64 netron seaborn==0.11.2 watchdog==2.1.5 utm==0.7.0 psycopg2 jedi pyapriltags

# install pytorch with CUDA 12.8 support 
RUN python3.10 -m pip install --ignore-installed sympy==1.13.3 
RUN python3.10 -m pip install --no-cache-dir torch --extra-index-url https://download.pytorch.org/whl/cu128
# monaco editor
RUN python3.10 -m pip install black==24.10.0

# websocket server dependency
RUN python3.10 -m pip install websocket_server==0.6.4 posix-ipc==1.1.1 django==4.1.7 djangorestframework==3.13.1 \
  django-webpack-loader==1.5.0 django-cors-headers==3.14.0 websockets==11.0.3 asyncio==3.4.3

# BT STUDIO hotfix
RUN python3.10 -m pip install py-trees autopep8
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg \
  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null \
  && apt-get update && apt-get install -y \
  ros-humble-py-trees \
  ros-humble-py-trees-ros


# Create workspace and add drone packages
RUN echo "source /usr/share/gazebo/setup.bash" >> ~/.bashrc
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc

# Download and install OMPL library
COPY install-ompl-ubuntu.sh /
WORKDIR /
RUN chmod u+x install-ompl-ubuntu.sh
RUN ./install-ompl-ubuntu.sh --github --python || ./install-ompl-ubuntu.sh --github --python

