FROM jderobot/robotics-applications:dependencies-humble

WORKDIR /

# RoboticsInfrasctructure Repository
ARG ROBOTICS_INFRASTRUCTURE=$ROBOTICS_INFRASTRUCTURE
RUN mkdir -p /opt/jderobot && \
    git clone --depth 1 https://github.com/JdeRobot/RoboticsInfrastructure.git -b $ROBOTICS_INFRASTRUCTURE /opt/jderobot

# create workspace and add Robot packages
RUN mkdir -p /home/ws/src
RUN mv /opt/jderobot/CustomRobots /opt/jderobot/jderobot_drones /home/ws/src/
RUN mv /opt/jderobot/resources /resources

ARG IMAGE_TAG
ENV IMAGE_TAG=${IMAGE_TAG}

# Clone the RoboticsApplicationManager repository into the src folder inside RoboticsAcademy
ARG RAM=$RAM
RUN git clone https://github.com/JdeRobot/RoboticsApplicationManager.git -b $RAM /RoboticsApplicationManager

# copy scripts
RUN mv -t / /opt/jderobot/scripts/.env  /opt/jderobot/scripts/entrypoint.sh /opt/jderobot/scripts/start_vnc.sh  /opt/jderobot/scripts/start_vnc_gpu.sh /opt/jderobot/scripts/kill_all.sh /opt/jderobot/scripts/test/check_device.py /opt/jderobot/scripts/set_dri_name.sh

# give execution permissions
WORKDIR /
RUN chmod +x /start_vnc.sh /kill_all.sh /entrypoint.sh /start_vnc_gpu.sh /set_dri_name.sh

# RoboticsAcademy
ARG ROBOTICS_ACADEMY=$ROBOTICS_ACADEMY
RUN git clone --depth 1 https://github.com/JdeRobot/RoboticsAcademy.git -b $ROBOTICS_ACADEMY /RoboticsAcademy/

# Compiling and sourcing the workspace
WORKDIR /home/ws
# RUN /bin/bash -c "source /home/drones_ws/install/setup.bash; rosdep install --from-paths src --ignore-src -r --rosdistro humble -y"
RUN /bin/bash -c "source /home/drones_ws/install/setup.bash"
RUN /bin/bash -c "source /opt/ros/humble/setup.bash; colcon build --symlink-install"

# Compress commons
WORKDIR /RoboticsAcademy/
RUN cd /RoboticsAcademy/common && cd console_interfaces && zip -r ../common.zip console_interfaces/ && cd .. && cd gui_interfaces && zip -r -u ../common.zip gui_interfaces/ && cd .. && cd hal_interfaces && zip -r -u ../common.zip hal_interfaces/ && cd ../.. && mv common/common.zip react_frontend/src/common.zip

# build react_fronted
RUN cd /RoboticsAcademy/react_frontend/ && yarn install && yarn run build

# Django server
EXPOSE 7164

# Manager websocket
EXPOSE 7163

# noVNC Console
EXPOSE 1108

# noVNC Gazebo
EXPOSE 6080

#PostgreSQL Database
EXPOSE 5432

WORKDIR /

# Setting environment in both interactive or non-interactive shells
ENV BASH_ENV /.env
ENTRYPOINT ["./entrypoint.sh"]