FROM jderobot/base:2.4

# Custom Robot Repository
RUN mkdir -p /opt/jderobot && cd /opt/jderobot && \ 
	git clone -b melodic-devel https://github.com/JdeRobot/CustomRobots.git

# JdeRobot drones
RUN mkdir -p /catkin_ws/src && cd /catkin_ws && catkin init && cd / && \
	git clone -b melodic-devel https://github.com/JdeRobot/drones.git && \
	git clone -b web-template https://github.com/JdeRobot/IndustrialRobots.git

# Install JdeRobot drones
RUN echo 'export ROS_WORKSPACE=/catkin_ws' >> ~/.bashrc
RUN cd /catkin_ws/src && ln -s /drones/drone_wrapper .
RUN cd /catkin_ws/src && ln -s /drones/drone_assets .
RUN cd /catkin_ws/src && ln -s /IndustrialRobots/industrial_robots .
RUN cd /catkin_ws/src && ln -s /IndustrialRobots/assets .
RUN cd /catkin_ws && rosdep update && rosdep install --from-paths . --ignore-src --rosdistro melodic -y && apt install ros-melodic-moveit -y
RUN /bin/bash -c '. /opt/ros/melodic/setup.bash; cd /catkin_ws; catkin build'

## Setting env vars
ENV GAZEBO_RESOURCE_PATH "$GAZEBO_RESOURCE_PATH:/usr/share/gazebo-9:/RoboticsAcademy/exercises/follow_line/web-template/launch"
ENV GAZEBO_PLUGIN_PATH "$GAZEBO_PLUGIN_PATH:/usr/lib/x86_64-linux-gnu/gazebo-9/plugins:/Firmware/build/px4_sitl_default/build_gazebo"
ENV GAZEBO_MODEL_PATH "$GAZEBO_MODEL_PATH:/usr/share/gazebo-9/models:/opt/jderobot/CustomRobots/f1:/opt/jderobot/CustomRobots/roomba_robot:/opt/jderobot/CustomRobots/3d_reconstruction:/opt/jderobot/CustomRobots/Taxi_navigator:/Firmware/Tools/sitl_gazebo/models:/opt/ros/melodic/share/drone_assets/models:/opt/ros/melodic/share/drone_assets/urdf:/drones/drone_assets/models:/IndustrialRobots/assets/models"
ENV LD_LIBRARY_PATH "$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/gazebo-9/plugins:/Firmware/build/px4_sitl_default/build_gazebo"

# RoboticsAcademy
RUN git clone https://github.com/predator4hack/RoboticsAcademy.git -b pick_place
# RUN rsync -a --exclude 'ace-builds' /RoboticsAcademy/exercises/static/exercises/* /RoboticsAcademy/exercises

COPY manager.py /manager.py
COPY instructions.json /instructions.json
COPY manager_utils.py /manager_utils.py

# execute permissions to start.sh
COPY start.sh /start.sh
COPY start_manager.sh /start_manager.sh
RUN chmod 755 /start.sh
RUN chmod 755 /start_manager.sh

EXPOSE 2303
EXPOSE 1905
EXPOSE 8080
EXPOSE 7681
EXPOSE 8765
EXPOSE 1108
# Port by WebRtc
EXPOSE 1831
# Port for noVNC
EXPOSE 6080
EXPOSE 6081