# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(837, 621)
        MainWindow.setMinimumSize(QtCore.QSize(660, 370))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 1200))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 410, 410))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mapLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mapLayout.setContentsMargins(0, 0, 0, 0)
        self.mapLayout.setObjectName("mapLayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(440, 40, 400, 400))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.tlLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.tlLayout.setContentsMargins(0, 0, 0, 0)
        self.tlLayout.setObjectName("tlLayout")
        self.getPathButton = QtWidgets.QPushButton(self.centralwidget)
        self.getPathButton.setGeometry(QtCore.QRect(50, 470, 131, 51))
        self.getPathButton.setObjectName("getPathButton")
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(270, 470, 101, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon)
        self.playButton.setObjectName("playButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(430, 470, 111, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon1)
        self.stopButton.setObjectName("stopButton")
        self.destinyLabel = QtWidgets.QLabel(self.centralwidget)
        self.destinyLabel.setGeometry(QtCore.QRect(30, 440, 61, 21))
        self.destinyLabel.setObjectName("destinyLabel")
        self.XLabel = QtWidgets.QLabel(self.centralwidget)
        self.XLabel.setGeometry(QtCore.QRect(100, 450, 21, 21))
        self.XLabel.setObjectName("XLabel")
        self.YLabel = QtWidgets.QLabel(self.centralwidget)
        self.YLabel.setGeometry(QtCore.QRect(220, 450, 21, 21))
        self.YLabel.setObjectName("YLabel")
        self.positionLabel = QtWidgets.QLabel(self.centralwidget)
        self.positionLabel.setGeometry(QtCore.QRect(440, 440, 61, 20))
        self.positionLabel.setObjectName("positionLabel")
        self.VLabel = QtWidgets.QLabel(self.centralwidget)
        self.VLabel.setGeometry(QtCore.QRect(530, 450, 21, 21))
        self.VLabel.setObjectName("VLabel")
        self.XValue = QtWidgets.QLabel(self.centralwidget)
        self.XValue.setGeometry(QtCore.QRect(130, 450, 41, 21))
        self.XValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XValue.setObjectName("XValue")
        self.VValue = QtWidgets.QLabel(self.centralwidget)
        self.VValue.setGeometry(QtCore.QRect(560, 450, 41, 21))
        self.VValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.VValue.setObjectName("VValue")
        self.YValue = QtWidgets.QLabel(self.centralwidget)
        self.YValue.setGeometry(QtCore.QRect(260, 450, 41, 21))
        self.YValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YValue.setObjectName("YValue")
        self.WValue = QtWidgets.QLabel(self.centralwidget)
        self.WValue.setGeometry(QtCore.QRect(700, 450, 41, 21))
        self.WValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.WValue.setObjectName("WValue")
        self.WLabel = QtWidgets.QLabel(self.centralwidget)
        self.WLabel.setGeometry(QtCore.QRect(660, 450, 21, 21))
        self.WLabel.setObjectName("WLabel")
        self.mapLabel = QtWidgets.QLabel(self.centralwidget)
        self.mapLabel.setGeometry(QtCore.QRect(20, 10, 341, 17))
        self.mapLabel.setObjectName("mapLabel")
        self.mapLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.mapLabel_2.setGeometry(QtCore.QRect(440, 10, 121, 17))
        self.mapLabel_2.setObjectName("mapLabel_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(759, 459, 71, 71))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.logoLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.logoLayout.setContentsMargins(0, 0, 0, 0)
        self.logoLayout.setSpacing(0)
        self.logoLayout.setObjectName("logoLayout")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 530, 521, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        # self.Plannerlabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.Plannerlabel.sizePolicy().hasHeightForWidth())
        # self.Plannerlabel.setSizePolicy(sizePolicy)
        # self.Plannerlabel.setObjectName("Plannerlabel")
        # self.horizontalLayout.addWidget(self.Plannerlabel)
        # self.plannerBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        # self.plannerBox.setObjectName("plannerBox")
        # self.horizontalLayout.addWidget(self.plannerBox)
        # self.RunTimeLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.RunTimeLabel.sizePolicy().hasHeightForWidth())
        # self.RunTimeLabel.setSizePolicy(sizePolicy)
        # self.RunTimeLabel.setObjectName("RunTimeLabel")
        # self.horizontalLayout.addWidget(self.RunTimeLabel)
        # self.runtimeBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        # self.runtimeBox.setProperty("value", 1.0)
        # self.runtimeBox.setObjectName("runtimeBox")
        # self.horizontalLayout.addWidget(self.runtimeBox)
        self.liftDropButton = QtWidgets.QPushButton(self.centralwidget)
        self.liftDropButton.setGeometry(QtCore.QRect(270, 550, 101, 51))
        self.liftDropButton.setObjectName("liftDropButton")
        self.gotoPointButton = QtWidgets.QPushButton(self.centralwidget)
        self.gotoPointButton.setGeometry(QtCore.QRect(50, 550, 131, 51))
        self.gotoPointButton.setObjectName("gotoPointButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Global Navigation"))
        self.getPathButton.setText(_translate("MainWindow", "Send Goal"))
        self.playButton.setText(_translate("MainWindow", "GO!"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.destinyLabel.setText(_translate("MainWindow", "Destiny:"))
        self.XLabel.setText(_translate("MainWindow", "X:"))
        self.YLabel.setText(_translate("MainWindow", "Y:"))
        self.positionLabel.setText(_translate("MainWindow", "Position:"))
        self.VLabel.setText(_translate("MainWindow", "X:"))
        self.XValue.setText(_translate("MainWindow", "0"))
        self.VValue.setText(_translate("MainWindow", "0"))
        self.YValue.setText(_translate("MainWindow", "0"))
        self.WValue.setText(_translate("MainWindow", "0"))
        self.WLabel.setText(_translate("MainWindow", "Y:"))
        self.mapLabel.setText(_translate("MainWindow", "MAP: double click for selecting your destiny."))
        self.mapLabel_2.setText(_translate("MainWindow", "Manual controler:"))
        # self.Plannerlabel.setText(_translate("MainWindow", "planner"))
        # self.RunTimeLabel.setText(_translate("MainWindow", "runtime"))
        self.liftDropButton.setText(_translate("MainWindow", "Lift/Drop"))
        self.gotoPointButton.setText(_translate("MainWindow", "Store new pallet"))

import resources_rc