TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.05

  # max_rotational_vel: 0.25
  # min_in_place_rotational_vel: 0.01

  max_vel_theta: 0.5
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0.4

  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_th: 3.2

  holomonic_robot: false