local_costmap:
  global_frame: map
  robot_base_frame: amazon_warehouse_robot/amazon_warehouse_robot::chassis
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.02
  transform_tolerance: 0.5
  planner_freqency: 1.0
  planner_patiente: 5.0