name: Frontend Lint Workflow

on:
  push:
    # paths:
    #     - "react_frontend/**"

jobs:
  setup-and-lint:
    name: Setup and Lint Frontend
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout your code
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "yarn"
          cache-dependency-path: react_frontend/yarn.lock

      # 3) Install Yarn globally (optional; setup-node gives you npm)
      - name: Install Yarn
        run: npm install --global yarn

      # 4) Install dependencies
      - name: Install frontend deps
        working-directory: react_frontend
        run: yarn install --frozen-lockfile

      # 5) (Optional) Run your dev server
      - name: Run ESLint
        working-directory: react_frontend
        run: npm run lint
